### ISSUE TITLE
[Publisher UI] Add a default vhost for API revision deploymment

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-apim#10041]
### Describe your problem(s)
A default value for vhost is not selected when deploying an API revision. This breaks the UX of the user.
<img width="671" alt="Screen Shot 2021-03-01 at 5 21 00 PM" src="https://user-images.githubusercontent.com/22365810/109494194-94da4800-7ab3-11eb-9f7e-802658f63435.png">

**Comment by sachithKay** [comment]
related https://github.com/wso2/product-apim/issues/10040

**Comment by uvindra** [comment]
I also encountered this issue. If there is no valid default value that can be specified for vhost then it should not show up as an option in the drop down out of the box. Currently vhost is the default value that is selected, so if the user makes no change it will used for publishing

**Comment by uvindra** [comment]
The option 'VHost' that shows up in the drop down list as shown in the above screenshot does not seem to be an actual option. When actually expanding the drop down list the only option available is _localhost_ out of the box. When the drop down list expanded the value 'Vhost' moves to the top of the drop down to become a label.

This seems to indicate that the expectation is that the user should manually select at least the localhost value from the drop down list in order to deploy the revision. But currently this is not validated as a mandatory field that needs to be selected. 

*Suggestions*
1. I think better to remove the VHost value showing up within the drop down list by default because it leads to confusion. Since it seem to be meant as a label it should be displayed above the drop down as such at all times.
2. Make the drop down list a mandatory field so users are forced to select a value for deploying a revision.
