### ISSUE TITLE
Error while starting APIM - Address already in use: bind java.net.BindException

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10067]
### Description:
```System may be unstable: HTTPS ListeningIOReactor encountered a checked exception : Address already in use: bind java.net.BindException: Address already in use: bind```
The above error message is displayed randomly when starting a fresh apim pack in windows. I terminated the apim execution and executed the batch file again and server started without any errors. This was observed randomly.
[wso2carbon.log](https://github.com/wso2/product-apim/files/6067553/wso2carbon.log)

### Steps to reproduce:

- In a windows machine download apim v4.0.0-alpha
- Extract and execute wso2server.bat

### Affected Product Version:
v4.0.0-alpha

### Environment details (with versions):
- OS: Windows 2019 server

**Comment by arunans23** [comment]
In Windows, the IO Reactors are initiating with an host address of 0:0:0:0:0:0:0:0. (IPv6 format). 

```
TID: [-1234] [] [2021-03-01 23:18:25,399]  INFO {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Pass-through HTTP Listener started on 0:0:0:0:0:0:0:0:8280
TID: [-1234] [] [2021-03-01 23:18:25,399]  INFO {org.apache.synapse.transport.passthru.PassThroughHttpMultiSSLListener} - Starting Pass-through HTTPS Listener...
TID: [-1234] [] [2021-03-01 23:18:25,415]  INFO {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Pass-through HTTPS Listener started on 0:0:0:0:0:0:0:0:8243
```

SSLprofile reload is trying to close an endpoint with the host address of 0.0.0.0 (IPv4). Since this [check](https://github.com/wso2/wso2-synapse/blob/v2.1.7-wso2v219/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/core/PassThroughListeningIOReactorManager.java#L397) is failing, the endpoint does not get closed which causes this issue.

**Comment by arunans23** [comment]
Since the default [listenerprofiles.xml](https://github.com/wso2/product-apim/blob/v4.0.0-alpha/modules/distribution/product/src/main/conf/listenerprofiles.xml#L22) has the bindaddress of 0.0.0.0, the comparison is failing. Adding 0:0:0:0:0:0:0:0 as the bind address in the listenerprofiles.xml, resolves the issue.

**Comment by arunans23** [comment]
Created a doc issue to track this https://github.com/wso2/docs-apim/issues/3492

**Comment by senthuran16** [comment]
When restarting the pack after updating `<bindAddress>` in `<APIM_HOME>/repository/resources/security/listenerprofiles.xml`, the `bindAddress` property is reverted. As of now, we don't have this property templated in [listenerprofiles.xml.j2](https://github.com/wso2/product-apim/blob/master/modules/distribution/product/src/main/resources/conf/templates/repository/resources/security/listenerprofiles.xml.j2#L24). 

We will have to expose a property in `deployment.toml` to configure this value. Until that, we will have update the `<bindAddress>` property in [listenerprofiles.xml.j2](https://github.com/wso2/product-apim/blob/master/modules/distribution/product/src/main/resources/conf/templates/repository/resources/security/listenerprofiles.xml.j2#L24).
