### ISSUE TITLE
Error when running db scripts with mysql 5.7

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#10147]
### Description:
<img width="663" alt="Screenshot 2021-03-05 at 11 34 42 AM" src="https://user-images.githubusercontent.com/47380453/110074699-a8352e00-7da7-11eb-9f1e-4a1a23d0eb02.png">

Above mentioned errors are thrown when we execute the db scripts of APIM 4.0.0-alpha with mysql 5.7. 
I was able to fix this by specifying the character set as latin1 during the database creation. If that step is mandatory, we have to update the documentation or fix the scripts.

Also once it is fixed, still there was an error running the AM_DB script.
```ERROR 1067 (42000) at line 1512: Invalid default value for 'UPDATED_TIME'``` 

### Steps to reproduce:
Run the db scripts for AM_DB and SHARED_DB inside the 4.0.0-alpha

### Affected Product Version:
apim-4.0.0-alpha

**Comment by CrowleyRajapakse** [comment]
I think this is the fix : https://github.com/wso2-extensions/apim-migration-resources/pull/83

Might need to do the same fix to carbon-apimgt

**Comment by hisanhunais** [comment]
```Invalid default value for 'UPDATED_TIME'```
Similar Issue: https://github.com/wso2/product-apim/issues/10337

This has been fixed with https://github.com/wso2/carbon-apimgt/pull/10021/commits/f24e640b0c5c8554399745f79651706c9f711be5

Migration Script has to be updated. https://github.com/wso2-extensions/apim-migration-resources/blob/master/migration-scripts/migration-3.2.0_to_4.0.0/mysql.sql#L162

**Comment by vithu30** [comment]
Got errors in following tables due to the same issue mentioned above, when running the scripts on MySQL 8.0:

- IDN_PASSWORD_HISTORY_DATA
- IDN_CORS_ORIGIN
- IDN_CORS_ASSOCIATION
- CREATE INDEX IDX_AT_AT ON IDN_OAUTH2_ACCESS_TOKEN(ACCESS_TOKEN);
- CREATE INDEX IDX_AT_RT ON IDN_OAUTH2_ACCESS_TOKEN(REFRESH_TOKEN);
- CREATE INDEX IDX_AC_AC_CKID ON IDN_OAUTH2_AUTHORIZATION_CODE(AUTHORIZATION_CODE, CONSUMER_KEY_ID);
- CREATE INDEX IDX_CORS_SP_APP_ID ON IDN_CORS_ASSOCIATION (SP_APP_ID);
- CREATE INDEX IDX_CORS_ORIGIN_ID ON IDN_CORS_ASSOCIATION (IDN_CORS_ORIGIN_ID);
- CREATE INDEX IDX_USER_RID ON IDN_UMA_RESOURCE (RESOURCE_ID, RESOURCE_OWNER_NAME, USER_DOMAIN, CLIENT_ID);

As in [1], we will make following change to ```IDN_PASSWORD_HISTORY_DATA``` table:

Current DDL:
```
CREATE TABLE IF NOT EXISTS IDN_PASSWORD_HISTORY_DATA (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  USER_NAME   VARCHAR(255) NOT NULL,
  USER_DOMAIN VARCHAR(127) NOT NULL,
  TENANT_ID   INTEGER DEFAULT -1,
  SALT_VALUE  VARCHAR(255),
  HASH        VARCHAR(255) NOT NULL,
  TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID),
  UNIQUE (USER_NAME,USER_DOMAIN,TENANT_ID,SALT_VALUE,HASH)
)ENGINE INNODB;
```

Suggested Change:
```
CREATE TABLE IF NOT EXISTS IDN_PASSWORD_HISTORY_DATA (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  USER_NAME   VARCHAR(127) NOT NULL,
  USER_DOMAIN VARCHAR(50) NOT NULL,
  TENANT_ID   INTEGER DEFAULT -1,
  SALT_VALUE  VARCHAR(255),
  HASH        VARCHAR(255) NOT NULL,
  TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID),
  UNIQUE (USER_NAME,USER_DOMAIN,TENANT_ID,SALT_VALUE,HASH)
)ENGINE INNODB;
```

As did in [1], the following indexes can be removed:

1. CREATE INDEX IDX_AT_AT ON IDN_OAUTH2_ACCESS_TOKEN(ACCESS_TOKEN);
2. CREATE INDEX IDX_AT_RT ON IDN_OAUTH2_ACCESS_TOKEN(REFRESH_TOKEN);
3. CREATE INDEX IDX_AC_AC_CKID ON IDN_OAUTH2_AUTHORIZATION_CODE(AUTHORIZATION_CODE, CONSUMER_KEY_ID);

Suggestions:

- Regarding the `IDN_CORS_ORIGIN` and `IDN_CORS_ASSOCIATION`, it is used in the CORS feature [2]. Need to check the usage of it in APIM usecase
- Regarding the index `IDX_USER_RID`, it is used when UMA grant type is used. Since UMA grant type is not supported by default in API Manager shall we remove this index?

[1] https://github.com/wso2/carbon-apimgt/pull/7789/files
[2] https://is.docs.wso2.com/en/latest/learn/cors/

**Comment by malinthaprasan** [comment]
Reduced the priority for beta release.
