### ISSUE TITLE
[Devportal] - UX imporovemnt - Subscribe to Applications from subscriptions page.

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#10175]
### Describe your problem(s)
When dealing with a large set of applications, the drop-down to pick an application becomes too long, and locating an application becomes troubling. The application owner is not displayed.

### Solution
Proposal 1 - Display the data using a MUI datatable and provide pagination and search capability. 

Pros
1 - Less number of clicks
2 - Information visible at a glance.
3 - Pagination
4 - Searchable, sortable

Cons
1 - Overkill if there are few Applications available

Proposal 2 - Provide a Searchable dropdown as the application owner as the secondary text.

Pros
1 - Searchable.
2 - Takes Lessspace.

Cons
1 - All information is not visible at a glance.

**Comment by tmkasun** [comment]
Small suggestion on the 
```
The application owner is not displayed.
```
IMO we should only show the application owner when the application sharing feature is enabled, This information is coming in the settings API
```
https://localhost:9443/api/am/devportal/v2/settings
```
![image](https://user-images.githubusercontent.com/3313885/110292594-7cb67b80-8013-11eb-971a-76b0d8a6bc66.png)

Otherwise, same user name will repeat under all the app names in the dropdown
