### ISSUE TITLE
Revision feature related issues

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#10187]
### Description:
The following issues can be found.

1.   Display in devportal property does not work 

We cannot turn on/off this toggle.

2. Revision drop-down only loads after refresh

You can create multiple revisions for the API. Unless you load the API, it won't load the revisions created for the drop down.

3. Go to the Endpoints tab and change the current API to a revision number. It always goes to the overview tab. 

4. Failed to delete revisions after reaching revision count and got the following error log line. 

ERROR - GlobalThrowableMapper org.wso2.carbon.apimgt.api.APIManagementException: Failed to delete registry artifacts

### Affected Product Version:
wso2am-4.0.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by CrowleyRajapakse** [comment]
1. We have already done the UI fix for this in the latest, we have do a redeployment to apply the toggle changes though.
2. Need to do the UI fix
3. Need to do the UI fix
4. This also present in the latest, seems to be a UI issue in the last revision create popup. When selected old revision to delete , it seems to get deleted successfully but the second request also seems to be a DELETE request instead of POST to create the new revision.
When done this manually using revision delete button, this issue doesn't occur.

**Comment by tmkasun** [comment]
We create a separate UI issue for the 1st one https://github.com/wso2/product-apim/issues/10332

**Comment by Krishanx92** [comment]
4th issue:
Fix: https://github.com/wso2/carbon-apimgt/pull/10052

**Comment by Krishanx92** [comment]
1st issue:
Fix https://github.com/wso2/carbon-apimgt/pull/10086
UI issues will address separately with https://github.com/wso2/product-apim/issues/10436 with dropdown revamp, hence closing this.
