### ISSUE TITLE
Error while deleting or editing resource of an API product

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10280]
### Description:
Following error message is displayed while trying to edit or delete resources of an created API product.
_"Error while updating the definition"_

![chrome-capture (4)](https://user-images.githubusercontent.com/32265029/111264383-a27beb80-85e4-11eb-9410-46797be3ba64.gif)

### Steps to reproduce:

- Create 2 APIs ( https://apim.docs.wso2.com/en/latest/learn/design-api/create-api-product/create-api-product/ )
- Create an API Product with the 2 APIs
- Go to overview page of the product.
- Click show more under Resources
- Delete an resource.

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10
- DB : MSSQL server 2019

#### Suggested Labels:
API-M 4.0.0

**Comment by CrowleyRajapakse** [comment]
This is due to a wrong redirection at the "Show More" in Overview page resources section. It redirects the user to a resource page of an API, not to the resource page of API Product. 

If we click the resources tab in the API Product and do the edit by clicking "Edit Resources", this issue doesn't occur.
