### ISSUE TITLE
Toggle per api rate limiting option does not work in Operation Governance for resources

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10352]
### Description:
After clicking the "Toggle per api rate limiting", it does not perform any action.
![image](https://user-images.githubusercontent.com/28702407/111615103-5dcf9a80-8806-11eb-9839-7ed4b55899ab.png)

### Affected Product Version:
API-M 4.0.0 Alpha

**Comment by kavishkafernando** [comment]
'Toggle per api rate limiting' button will scroll the page to the top (Scroll to the Operations Configuration section) where the user can manually select API Level.
![toggle](https://user-images.githubusercontent.com/19324135/111944069-ca93af00-8afc-11eb-9999-9a57002e2a40.gif)

There are a few UX issues for this feature.
- Toggle per api rate limiting wording is incorrect it should change to 'Change Rate Limiting Level'
- When Operation level is selected there is no additional action needed in the Rate limiting policy selection hence this option  is only needed at when API Level is selected 
- In order to make the experience better we can focus the operation level  radio option
