### ISSUE TITLE
Unable to pass mtls certificate in the Request header

### ISSUE THREAD

**Issue by malshaniS** [wso2/product-apim#10473]
### Description:
Getting the below error when sending valid mtls certificate in the Request header.

<img width="867" alt="112677521-daf6b180-8e8f-11eb-95e4-b292b2b5428c" src="https://user-images.githubusercontent.com/40388545/112792538-4c498680-9081-11eb-98e4-5a02e3d9ee7f.png">

### Steps to reproduce:
Send API GET request with mtls certificate in the header.
Eg:

> **Header:**
> Content-Type: application/json
> Authorization: Bearer <>
> **X-WSO2-CLIENT-CERTIFICATE: <'tls header'>**

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dushaniw** [comment]
@uvindra this is related to the extension listener we have introduced. https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/ext/listener/ExtensionListenerUtil.java#L167

Here we get the cert from the message context pass it to the extension point. Need to update this for cases where cert is sent in the header as well. We might need to refactor the logic of getting and setting the cert from MutualSSLHandler.

**Comment by uvindra** [comment]
I was able to get this to work on APIM 4.0.0 **9.0.95_SNAPSHOT** as follows,

Steps followed
=======================================
1. Run the following commands to generate a self signed key pair
	
	openssl genrsa 2048 > test.key
	chmod 400 test.key
	openssl req -new -x509 -nodes -sha256 -days 365 -key test.key -out test.cert
	
2. Do the following changes to <APIM_HOME>/repository/conf/deployment.toml and start APIM
``` 
	[apimgt.mutual_ssl]
 	# This property needs to be true if the MutualSSL connection is established between the load balancer and the Gateway.
 	enable_client_validation = false
 	#This property needs to be true if the certificate should be decoded when it is passed from the load balancer to the Gateway.
 	client_certificate_encode = true
```
 	
   Since we are making this call direclty via curl, we need to set `client_certificate_encode = true` so that Gateway will recongnize that the certificate is encoded in the header.
	
2. Create a new API in super tenant that points to a mock back end do the following changes
	- In Transport level security, tick Mutual SSL and select Mandatory
	- Attach the above generated test.cert with the alias 'abc'
	- In Application level security, select OAuth2 as optional(To eliminate the need to send access token for API invocation)
![image](https://user-images.githubusercontent.com/6614042/113280462-f0416500-9301-11eb-81bd-2e4f2c76839f.png)
	

3. Save, deploy a new revision and Publish the API

4. Run the following command in the <APIM_HOME>/repository/resources/security folder

	`keytool --list --keystore client-truststore-temp.jks --alias abc_-1234`
	
   This should display an output displaying the Certificate fingerprint, which indicates that the cert has been saved in the trust store.
   
5. Wait approximately 10 minutes to allow the cert to be loaded into memory(Watch for the message `PassThroughHttpMultiSSLListener  PassThroughHttpListener reloading SSL Config..` in the wso2carbon.log)

6. base64 encode the test.cert and invoke the API with curl, including the value in the `X-WSO2-CLIENT-CERTIFICATE` header as shown below,

	`curl -k --location -X GET 'https://localhost:8243/<context>/<version>/<resource>' -H 'X-WSO2-CLIENT-CERTIFICATE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1ekNDQXMrZ0F3SUJBZ0lVU2V5Z0JrZVprYVBpRC9JRUZJbVdaYm52OGZNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZSXhDekFKQmdOVkJBWVRBa3hMTVJBd0RnWURWUVFJREFkWFpYTjBaWEp1TVJBd0RnWURWUVFIREFkRApiMnh2YldKdk1RMHdDd1lEVlFRS0RBUlhVMDh5TVEwd0N3WURWUVFMREFSQlVFbE5NUkF3RGdZRFZRUUREQWQxCmRtbHVaSEpoTVI4d0hRWUpLb1pJaHZjTkFRa0JGaEIxZG1sdVpISmhRSGR6YnpJdVkyOXRNQjRYRFRJeE1ETXoKTVRFd016STBNVm9YRFRJeU1ETXpNVEV3TXpJME1Wb3dnWUl4Q3pBSkJnTlZCQVlUQWt4TE1SQXdEZ1lEVlFRSQpEQWRYWlhOMFpYSnVNUkF3RGdZRFZRUUhEQWREYjJ4dmJXSnZNUTB3Q3dZRFZRUUtEQVJYVTA4eU1RMHdDd1lEClZRUUxEQVJCVUVsTk1SQXdEZ1lEVlFRRERBZDFkbWx1WkhKaE1SOHdIUVlKS29aSWh2Y05BUWtCRmhCMWRtbHUKWkhKaFFIZHpiekl1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBczVQLwplOXFpTjJQRFJKRk1WekZaQVo5NlVzRzhjMDFMbFJXNUNHWktINWxLOGtnT01kcEx0aUtzZ0NuWCswT3pjcndECjhwL09zOXoyak5yT2YzWmJNUkR3MS9JdDEvK0lPUlhOQXpaMmcvZWd2dmxmTjhvckY4a0NWa3JxRTBybXlpVzMKZXlpQmZkMndybzFhTTBRbWl5SURoM203b2g4ZWk2dHVVVTlwWGJ2TWF0OStmVDc0Kzg2N3lveFZNNUVNZWVmZQpGZzJ2dmlaS3lWVFZSRlo1YUh0V1RZTlRJS2dQRFRGd3psZjdxVlZXd2xLY0gxR3VNZ3lkR2E4bVRvZEVRR2NMCm9WbnNuazM1OHErcHg3Qmg0eENZdTdDV3QzVVRVZU1NNCtjM1kySUcyVjF0dHcveTlEbXNXNjF2b1VsTDRZcGsKMjFIS0t3dEdWemNNeHVLelFRSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVtb0NUMVZ4VU1TYjdMMFdHaEt1dQpvb2M4UVNzd0h3WURWUjBqQkJnd0ZvQVVtb0NUMVZ4VU1TYjdMMFdHaEt1dW9vYzhRU3N3RHdZRFZSMFRBUUgvCkJBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVFnb0VVV3FrN3dOdEw3K1UrL1l5bWNrL005UngKZlQ2QUdMdWEzS0VyQXJtSGZ2bHdJVDFXR0QyR0dHcXBVNmZ2Z0VHbDBPUFdodzkzMGRCcXpyenZ6aGltc1J5VApibC9nOEF2dFZxa0k5Tk1vdFpRd2h4NDd2RWNIbnQ3MG1LT3lvVDJXcktvcUNlK0JybDRtQ1NCbkdLMnp5RnI2CmpFWFg2aC9yQUJTWmUxTGtnMmF2amh6YW5SMnJEdDdsLytWem43QVgxL1dqWnY4VGk0N3hqQTRsNENHaGRLWTUKNEFpVDZzdFJ4b0hQNzRlR3JpOXFUS1BjRGZiUmRYM1hyZE9iSXJtZHNNcHV4WG9qSENmdlZOcDM4ODdmdUVYZQpsUElwTm8yUXRBbFRuSW9sSE1lZURacXNOdkFMOGt5QmN4S2lSeWowQW50aW5SR3FWMlU5R0wvNjJRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo='`
	
   Invocation is successful.

**Comment by malinthaprasan** [comment]
Reduced the priority for beta release. This will be taken after beta.
