### ISSUE TITLE
Can't create new scope assignments

### ISSUE THREAD

**Issue by praminda** [wso2/product-apim#10498]
### Description:

Automatically logs out of the `/admin` when creating new scope assignements
### Steps to reproduce:
1. Create an empty role in carbon console
2. Sign in to `/admin` as super admin
3.  Go to scope assignments and try to create a scope mapping for the new role
4. When submitting it give an error bubble an does a relogin
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): APIM test setup

**Comment by malinthaprasan** [comment]
I think this happens because everyone is using the same admin user when testing. So when generating a token, everyone will get the same token as we don't do a session based login. When someone logs out, the token will be revoked, resulting in others next API request to fail and logout from the portal.
