### ISSUE TITLE
Error while viewing APIs on Publisher

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#10492]
### Description:
Getting below error while trying to view details of an API in publisher. This does not happen on Chrome, only on safari.
<img width="1467" alt="Screenshot 2021-03-30 at 10 28 55" src="https://user-images.githubusercontent.com/28379317/112936777-128d8400-9144-11eb-9560-f97fd5036536.png">

### Steps to reproduce:
1. Go to Publisher and click on an API (using Safari)

### Environment details (with versions):
- Browser : Safari

**Comment by tmkasun** [comment]
This could happen due to the browser cache, I tested in 
![image](https://user-images.githubusercontent.com/3313885/113722755-5bc67080-970e-11eb-951c-3d59906a6be7.png)
safari version and couldn't re-produce this issue.

  Apparently, the browser is having an old/outdated index.html (base page) and it has tried to fetch the JS app chunks with old hash keys.
This could have prevented with appropriate cache headers in the base page response.

Let's keep this issue open to further look into the issue and find a solution, Ideally, app should not crash due to caching issues

**Comment by nandika** [comment]
Closing the issue as there is not updated on this one
