### ISSUE TITLE
Content search by a tag name returns no API

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#10504]
### Description:
Searching by tag name does not return any API. (prefix search tag:<tag_name> returns the result correctly)

### Steps to reproduce:
1. Create an API, and attach a tag.
2. Execute a content search by the tag name
3. No API is listed

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by YasasRangika** [comment]
This issue is in progress

**Comment by YasasRangika** [comment]
Tags are saved as type of properties in solr. Since in api /search it perform a attribute search we can not search for those properties directly with the same call. So as an alternate solution for this we can use tags:<tag_name> when searching by tags. 

Since the current product consists of this solution as mentioned in [docs](https://apim.docs.wso2.com/en/4.0.0-dev/reference/product-apis/publisher-apis/publisher-v2/publisher-v2/#operation/getAllAPIs), we can close this issue.
