### ISSUE TITLE
User with a internal/publisher role can navigate to the Runtime configs even though its not permitted, Better to hide it from the portal UI

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim#10548]
### Describe your problem(s)
When a user with only internal/publisher permission login to the publisher portal and try to navigate to the runtime configs section, the UI gives the following error.

![screenshot-apislb-apim-com-publisher-apis-a323b48c-c499-402c-8347-d7d7a9b0c986-runtime-configuration-1617084162611](https://user-images.githubusercontent.com/42435576/112941866-df9bbe00-914c-11eb-9c8f-571dee21ce6f.png)

If a user with a publisher role doesn't have the permission to change the Runtime configs of an API, its better if we can hide that section for such a user.

### Describe your solution
Hide the Runtime configs section for a user that has only publisher permissions.

### How to reproduce it
1. Log in to the publisher portal as an admin user and create a new API.
2. Log out from the publisher portal.
3. Create a new user that has only internal/publisher permissions.
4. Then log in to the publisher portal with that new user.
5. Try to navigate to the **Runtime** section.

---

**Comment by malinthaprasan** [comment]
security:
        - OAuth2Security:
            - apim:api_view

Lets add above to /key-manager GET in publisher

**Comment by Sarangan0219** [comment]
Users with a publisher role can view the API configs Nah? We are specifically showing the message of  **You are not authorized to update particular fields of the API due to insufficient permissions** in runtime configs so the user will get the idea that he is not allowed to change the configs but can view the available ones.

![Screenshot from 2021-04-11 11-01-30](https://user-images.githubusercontent.com/60866295/114293670-b288cd00-9ab5-11eb-8cca-51423ae8461e.png)

We have this behavior for all the other sections too.

**1. Endpoints**

![Screenshot from 2021-04-11 11-03-39](https://user-images.githubusercontent.com/60866295/114293713-e7951f80-9ab5-11eb-9d18-c272361807b4.png)

**2. Design Configurations**

![Screenshot from 2021-04-11 11-06-51](https://user-images.githubusercontent.com/60866295/114293733-16ab9100-9ab6-11eb-8be1-d080bf8ab74c.png)
