### ISSUE TITLE
No way of replying to an existing comment reply

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#10631]
### Describe your problem(s)
Users can comment on features and users can reply to the comment. What if there is a conversation going on and the user whats to reply to a specific comment that happens to be a reply. It will be great if there was a way to tag a comment or a user in the reply, so that there is some connection.

In the following example Mary wants to Kim's comment, which he added in the form of a reply.

<img width="1680" alt="Screenshot 2021-03-30 at 13 30 25" src="https://user-images.githubusercontent.com/5195851/112954684-41afef80-915c-11eb-96cc-9a52650b1890.png">

### How will you implement it

---

**Comment by tmkasun** [comment]
@Mariangela 
Can you please elaborate on this 

> Users can comment on features

What do you mean by `features`?

> . . . tag a comment or a user . . .

Yes, I too agree  with this, But it's technically a bit complicated to implement such thing, 
Because:
- We need to keep the **mentioned** username and **commentID** along with the message and write some visualization logic to appear them as comment link/user mentions 
- Have to handle the pagination etc 

ATM we could highlight the message if it has **@<user+name>** up to a white space character but there won't be any link
