### ISSUE TITLE
Advance throttling --Request count does not throttle 

### ISSUE THREAD

**Issue by dnwick** [wso2/product-apim#10643]
### Description:
Note : This is working some users but for me it did not. Below are user credentials

Should check on PizzaShack-damith :1.0.0 api

u.n - damith
p.w - damith@123

you can check this with hosted distributed setup. Tested with two throttle policies created 
 - damithReqCountPolicy
 -  dnwickThrottle1
 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
Reduced the priority because the issue is not always reproducible.

**Comment by dushansilva** [comment]
Hi damith, I noticed that the request count used in. the policies is 5 &. 3 respectively. I assume that the reason you did not experience a throttle out as soon as you reached limit could be that the request count is too low, 

since we have something like a periodic timer which checks if the api is throttle out, by the time you reach the count the timer has not yet market it as throttled out. You can try testing this scenario again with high values such as 15 or 20,

**Comment by malinthaprasan** [comment]
What is the timewindow used here?
5 req per 1 min and 3 req per 1 min?

**Comment by dushansilva** [comment]
yes its 5 req per min and 3 req per min

**Comment by malinthaprasan** [comment]
Hmm, the request should be throttled out at least after some requests even though it is greater than 3 or 5..
@dnwick did we create a revision and deploy the API after adding these policy changes? 
Seems like the API already deleted in the distributed setup now..

**Comment by dnwick** [comment]
Yes did several times. Anyways others could throttle out. If this is not reproducible lets park it for now

**Comment by malinthaprasan** [comment]
please reopen if you come across this again
