### ISSUE TITLE
Cannot change ownership of applications to users with custom subscriber roles 

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#10640]
### Description:

Cannot change ownership of applications to a user who has a custom role mapped to internal/subscriber role. If we create another user and directly assign "internal/subscriber" role, can change ownership to him.
### Steps to reproduce:

1. Create "user1"
2. Create "role1"
3. Map scopes of internal/subscriber to role1 from Admin portal.
4. Create "user2" and assign internal/subscriber role.
4. Log into Devportal as user2
5. Create App1
6. Log into same tenant admin portal as an admin
7. Go to the Applications menu and search for "App1" and change ownership from user1 to user2

### Affected Product Version:
API-M 4.0.0 Alpha

**Comment by wasuradananjith** [comment]
I followed the below steps.

1. Create "user1"
2. Create "role1" and assigned it to "user1"
3. Map scopes of internal/subscriber to role1 from Admin portal.
4. Create "user2" and assign Internal/subscriber role.
4. Log into Devportal as user2
5. Create App2
6. Log into Devportal as user1. **You will be unable to login.**
7. Restart the server.
8. Now again login into Devportal as user 1. You will be able to successfully logged in.
9.  Create App1
10. Log into the same tenant admin portal as an admin
11. Go to the Applications menu and search for "App1" and change ownership from user1 to user2. It will be successful.
12. Go to the Applications menu and search for "App2" and change ownership from user2 to user1. It will be successful.

The problem here was the changes in the tenant-conf.json have not been reflected. After the restart, the changes must have got reflected. So the issue that should fix is updating the tenant-conf.json on the fly, without restarting the server.

**Comment by wasuradananjith** [comment]
> I followed the below steps.
> 
>     1. Create "user1"
> 
>     2. Create "role1" and assigned it to "user1"
> 
>     3. Map scopes of internal/subscriber to role1 from Admin portal.
> 
>     4. Create "user2" and assign Internal/subscriber role.
> 
>     5. Log into Devportal as user2
> 
>     6. Create App2
> 
>     7. Log into Devportal as user1. **You will be unable to login.**
> 
>     8. Restart the server.
> 
>     9. Now again login into Devportal as user 1. You will be able to successfully logged in.
> 
>     10. Create App1
> 
>     11. Log into the same tenant admin portal as an admin
> 
>     12. Go to the Applications menu and search for "App1" and change ownership from user1 to user2. It will be successful.
> 
>     13. Go to the Applications menu and search for "App2" and change ownership from user2 to user1. It will be successful.
> 
> 
> The problem here was the changes in the tenant-conf.json have not been reflected. After the restart, the changes must have got reflected. So the issue that should fix is updating the tenant-conf.json on the fly, without restarting the server.

Adding to the above, according to [1], 

**_If you get a "Error while updating ownership to <username>" error (e.g., Error while updating ownership to Kim) in the Admin Portal, make sure to request that specific user (e.g., Kim) to sign in to the WSO2 Developer Portal, because users are not added as subscribers until they sign in to the Developer Portal at least once._**

So the error that observed here is expected. Thus confirms that the only thing that should be fixed is the **7th step - Log into Devportal as user1. You will be unable to login.**.

[1] https://apim.docs.wso2.com/en/latest/learn/consume-api/manage-application/advanced-topics/changing-the-owner-of-an-application/#changing-the-owner-of-an-application

**Comment by malinthaprasan** [comment]
Will be taken after beta release.
