### ISSUE TITLE
Resources View not update when changing revisions.

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#10745]
### Description:
Create API by applying two API tiers in different revisions.
Change revision and check the ui.

**Comment by Krishanx92** [comment]
The resource view is updating but not the API tier view. I think it's because
 API tier populates value from  **apiThrottlePolicy** and it won't change with revision change.


![Screenshot from 2021-04-05 09-30-19](https://user-images.githubusercontent.com/8374895/113535769-f8472080-95f1-11eb-8f07-0dab5633c2fa.png)
