### ISSUE TITLE
Tooltip needs to be fixed

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#11038]
### Description:

tooltip needs to be corrected. 

Configurations*
require*

and is there a better replacement for "to affect"? @Mariangela 

![image](https://user-images.githubusercontent.com/3960742/115002180-10f0e980-9ec2-11eb-94e4-1e24de90eba7.png)

**Comment by Mariangela** [comment]
@bhathiya , the answer to your question would be "reflect".
"Changes made in the API Configurations section require a new deployment in order to be reflected in the Gateway."


@bhathiya & @tmkasun  - 
Instead of correcting the existing tooltip. How about replacing it with one of the following options?
I feel like option [1] is more user friendly.

[1] If you update the API configurations, make sure to deploy a new revision.

[2] When API configurations are updated, it is mandatory to deploy a new revision.

**Comment by tmkasun** [comment]
@Mariangela , i'm +1 to 1st option, It's simple and to the point , thanks

**Comment by bhathiya** [comment]
Shall we combine the 2 to say why?

`If you update the API configurations, make sure to deploy a new revision (in order?) to reflect the changes in the Gateway.`

**Comment by Mariangela** [comment]
I personally feel that the sentence should be as short as possible and address what needs to be done. I feel that all addition explanations to explain the why aspect should be addressed properly in the APIM 4.0.0 documentation. 

However, if need want to combine the two sentences, I would propose the following: 

"If you update the API configurations, make sure to deploy a new revision so that the changes get reflected in the Gateway."

**Comment by bhathiya** [comment]
+1. @tmkasun

**Comment by tmkasun** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/10420 hence closing
