### ISSUE TITLE
[3.1.0] Swagger Definitions are not Updated

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#11240]
### Description:

The Swagger definitions are not getting updated as expected when trying to save the configurations from the Resource view in the Publisher portal. Whereas, when tried saving the configurations from the Runtime Configurations view, the Swagger is getting saved as expected and the local-entries are getting updated. Please find the steps to reproduce below.

### Steps to reproduce:

- Start the API Manager 3.1.0 server (+1620925753694)
- Log in to the Publisher portal and publish a Mock API
- Change the Throttling Policy from Operation Level to API Level and change the Unlimited to any other policy level and save the changes
- The API Definition page and the local-entries will not have the changes made to the Policies
- Navigate to Lifecycle view and ReDeploy the API, again the changes were not reflected as expected
- Navigate to Runtime Configuration view and Save the API. Now the changes will be reflected as expected

### Affected Product Version:

- API Manager v3.1.0 (+1620925753694)

**Comment by msm1992** [comment]
@athiththan11 the issue reported here is the expected behaviour. This will not affect throttling in APIM runtime as the tiers are not fetched from the API definition or the local entry. However the change being saved on saving the API through 'Runtime Configurations' page is a bug and need to be fixed.
