### ISSUE TITLE
[APIM v3.1.0] - Limited view of throttling tiers in Publisher portal

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#11291]
### Description:
In APIM v3.1.0 (latest WUM 1621832490148), there is a default limit of 25 when listing the advanced throttling tiers per API and Operational level. It is rendering via the following REST API.
**GET /api/am/publisher/v1/throttling-policies/api?limit=25&offset=0**

This REST API is called which has a default limit of 25[1]. So if the tier count is greater than 25 per tenant domain, the relevant tiers cannot be viewed via the Publisher portal.

[1] https://apim.docs.wso2.com/en/3.1.0/develop/product-apis/publisher-apis/publisher-v1/publisher-v1/#tag/Throttling-Policies

### Affected Product Version:
3.1.0

**Comment by chanaka3d** [comment]
Base on the offline discussion with Kasun, the dropdown needs to be replaced with an Autocomplete MUI component.
<img width="461" alt="Screen Shot 2021-06-28 at 3 55 45 PM" src="https://user-images.githubusercontent.com/3424539/123622220-9c271d80-d829-11eb-9725-b8ce1c5f84ca.png">
<img width="315" alt="Screen Shot 2021-06-28 at 3 55 36 PM" src="https://user-images.githubusercontent.com/3424539/123622230-a0533b00-d829-11eb-93e9-9648dbfb8ca4.png">

In order to do this, we need to have the search capability from the REST API side.

https://apim.docs.wso2.com/en/latest/reference/product-apis/publisher-apis/publisher-v2/publisher-v2/#operation/getAllThrottlingPolicies

This API does not support searching capability. This needs to be provided in order to continue with the UI.

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/apim-apps/pull/13
