### ISSUE TITLE
South Africa region is not supported when adding an AWS Lambda endpoint.

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-apim#11355]
### Description:
When trying to add an AWS Lambda endpoint from the Publisher, the South Africa region is not available in the dropdown.

### Affected Product Version:
wso2am-3.2.0

#### Suggested Labels:
wso2am

**Comment by binodmx** [comment]
Please find the below summary of the fix for this issue.

Patch Number: WSO2-CARBON-PATCH-4.6.0-1160
Update Number: 1561
Pull Requests:
https://github.com/wso2-support/carbon-apimgt/pull/3489
https://github.com/wso2-support/carbon-apimgt/pull/3490 (x-full)
https://github.com/wso2-support/update-artifacts/pull/1403
