### ISSUE TITLE
[3.2.0] Inconsistent behaviour when an Internal/publisher user try to edit the Runtime Configurations of an API Product

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#11655]
### Description:
After creating an API Product, if a user with the **Internal/publisher** role goes to check the Runtime Configurations of that API Product he/she will be shown an Unauthenticated request error in the UI as shown below.

![image](https://user-images.githubusercontent.com/25246848/133054549-a8c097a7-8053-432f-980f-8567b6b845fc.png)

Even though that error is displayed, the user can edit the API Product and click on Save without a problem. This behaviour is confusing and need to be fixed in a consistent manner.

### Environment details (with versions):
- OS: Ubuntu 20.04.2 LTS

**Comment by HiranyaKavishani** [comment]
This is expected when using the same browser due to cookies/headers which include partial tokens of REST API. When you logout from the previous user the token will be revoked. But if the browser tries to send the token which is already revoked and this situation happens.

Related issue [1] 
[1] https://github.com/wso2/product-apim/issues/10601
