### ISSUE TITLE
Endpoint validation option not working properly

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#11862]
### Description:
Even though the correct endpoint is provided, when the validation option is clicked (the tick), it shows a 404 not found error.

<img width="1415" alt="Screenshot 2021-10-12 at 10 21 21 PM" src="https://user-images.githubusercontent.com/5195851/137011782-a879dee9-f274-4037-9470-6a4471e539ff.png">

### Steps to reproduce:

1) Follow [1] to create a REST API from an OpenAPI definition by giving the following details.

     | Field    | Sample value                        |
     |----------|-------------------------------------|
     | OpenAPI URL | https://petstore3.swagger.io/api/v3/openapi.json |
     | Name     | SwaggerPetstore                     |
     | Context  | /petstore                            |
     | Version  | 1.0.6                               |
     | Endpoint | https://petstore3.swagger.io/api/v3 |

2) Click the tick next to the endpoint URL option to validate it.

[1] https://apim.docs.wso2.com/en/latest/design/create-api/create-rest-api/create-a-rest-api-from-an-openapi-definition/

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Mariangela** [comment]
@uvindra & @nuwand , please let me know your thoughts with regard to this feature. 
I feel that if there is no strong usecase for it that we should look at removing it in API-M 4.1.0 as opposed to just keeping it for the sake of it.

**Comment by uvindra** [comment]
This feature will work as expected under the following conditions,

1. The root endpoint URL specified must be a supported resource
2. It should support HEAD requests

But there is no guarantee that the above will be true for all endpoints. There is no way of determining this before hand and it will vary from endpoint to endpoint. So due to violation of at least one of the above conditions, even though the correct endpoint value is specified the validation will fail.

**Comment by Krishanx92** [comment]
Closing with above comment.
