### ISSUE TITLE
API Manager do not terminate the connection when the access token is revoked

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/product-apim#12413]
### Description:
Please refer: `<Censored>`

API Manager 3.2.0 do not terminate existing Web Socket connections when the access token is revoked / expired.

### Steps to reproduce:
- Create a WS app with a specific backend
- Obtain the access token and access the WS API. The WS backend should constantly send messages to the client. A sample WS backend is available in `<Censored>` with instructions on how to run).
- Revoke the access token (
  ```
  curl --location --request POST 'https://localhost:8243/revoke' \
  --header 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' \
  --header 'Authorization: Basic <BASE_64_CLIENT_ID:BASE_64_CLIENT_SECRET> \
  --data-raw 'token=<ACCESS_TOKEN>&token_type_hint=access_token&client_id=<CLIENT_ID>'
  ```

You will notice that the WS connection still persists.

### Affected Product Version:

- WSO2 API Manager 3.2.0

### Environment details (with versions):
- OS: Any
- Client: `<Censored>`
- Env (Docker/K8s): Any

---
#### Related Issues:

- https://support-internal.wso2.com/jira/browse/APIMINTERNAL-1656

#### Suggested Labels:
patch, Security, APIM320, critical, P2

#### Suggested Assignees:
N/A

**Comment by vidurananayakkara** [comment]
Patch issue: https://support-internal.wso2.com/jira/browse/APIMINTERNAL-1669
CS ticket: https://wso2.service-now.com/now/workspace/agent/full-search/BNYMELLONPROD-664
APIM Internal ticket: https://support-internal.wso2.com/jira/browse/APIMINTERNAL-1656

**Comment by slarti-b** [comment]
This issue (I think it's this issue anyway) constitutes a breaking change to the extent that we are looking at other components now for our API Manager. (It's a "last straw" kind of thing, but still, this was our last straw I think)

Previously (we ran 2.6 for a long time) we could connect a web socket and use that connection for days or even months.  We built a notification system to allow system-to-system integrations using this.  The third party connects and subscribes to a event feed and we send out notifications when stuff changes.

Now, in 4.2, the web socket connection gets disconnected when the access token expires (default 1 hour).  This breaks the integration.

I can understand the logic around revocation, but I don't think it's fully thought through.  As a comparison, if I make a REST call with an access token that expires in 5 seconds, and the API takes a long time to process it (say 20 seconds) then my access token has expired before I get a response.  But I still get the response, because it was valid when I connected.  An _access_ token controls access.  When you connect.  If my password expires on my computer, I can't log in anymore but I'm not thrown out in the middle of working at the instant the password expires.  

I can understand the other view, but I think both are valid and, given the breaking nature of this change, at a minimum it should have been possible to configure if this behaviour was desired or if the access token should only be validated when establishing the connection.
