### ISSUE TITLE
Email notifications are not sent

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/product-apim#12467]
### Description:

Email notifications are not sent to the subscribers in case of a new API version release after enabling email notifications

### Steps to reproduce:

1. Follow the [documentation](https://github.com/wso2/docs-apim/blob/master/en/docs/design/api-versioning/enabling-notifications.md) to enable email notifications
2. Publish a new API
3. Create a new user ( Add an email address to the user profile also ) and subscribe to the newly published API
4. Release a new version of the API
5. User should be notified via an email about the new API version

### Affected Product Version:

APIM-4.1.0-alpha

### Environment details (with versions):
- OS: MacOS Big Sur ( 11.6 )
- Client: Local

**Comment by CrowleyRajapakse** [comment]
Here, you need to not only create a new version but also need to deploy and publish the new version in order to receive the email.
The email notifier is engaged at API published state.
<img width="1680" alt="Screenshot 2022-03-01 at 12 29 59" src="https://user-images.githubusercontent.com/23296184/156120694-15a7b61d-59ad-4835-956c-94e23a7f1e70.png">

**Comment by IsuruMaduranga** [comment]
I did deploy and change the lifecycle state to publish. Tried several times also

**Comment by zqh0104** [comment]
I also encountered this problem, have you solved it?

**Comment by Tharanidk** [comment]
Yes, this is solved and can get email notifications following the above-mentioned steps.
