### ISSUE TITLE
Cannot disable resident keymanager

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#12602]
### Description:
When there is an external keymanager is configured, I cannot disable the resident keymanager. 

### Steps to reproduce:
1. Configure external keymanager
2. publisher and deploy the API 
3. Go to the dev portal and create an app and check the token generation page. you will see resident km and the external Km
4. Now go to the publisher and select the API and change the 'Application level security' to Allow selected and remove the resident KM
5. publish and deploy the api
6. create new app and check the token generation page 

<img width="920" alt="Screenshot 2022-03-09 at 8 59 20 AM" src="https://user-images.githubusercontent.com/4861150/157367640-899ca09d-bd49-4554-809b-2d2c158c9c2c.png">
<img width="696" alt="Screenshot 2022-03-09 at 9 01 33 AM" src="https://user-images.githubusercontent.com/4861150/157367656-c8ff4519-71a7-4898-a902-00199cd6964d.png">

Tried this on the tenant user. check ST as well

**Comment by tharikaGitHub** [comment]
Disabling the key manager tabs in the Applications page based on the runtime settings of an API is not the expected behaviour and it cannot be done. Hence we have done the fix in the Subscriptions page of a particular API. When someone does key generation for an API through the subscriptions page, the restrictions applied on the Runtime configurations will apply.
