### ISSUE TITLE
The SQL query for the user session insertion is not compatible with older versions of the DB2 database server

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/product-apim#12844]
### Description:
User login/SSO failure in the APIM 3.1.0 when the older version (such as DB2 v11.1.3.3) of the DB2 database is configured as the WSO2AM_DB database.

### Steps to reproduce:

- Configure 3.1.0  latest update (126) with an older version (such as v11.1.3.3) of the DB2 WSO2AM_DB DB
- Start the APIM server and try to log in to the publisher/devportal.
- The user will be redirected to retry.do

### Affected Product Version:
3.1.0
3.2.0

**Comment by shilmyhasan** [comment]
The fix is related only to DB2 version prior to 11.5. Public fix not associated as the above version is not compatible with latest versions of both IS and APIM.
IS- [https://is.docs.wso2.com/en/latest/deploy/environment-compatibility/#tested-dbmss](https://is.docs.wso2.com/en/latest/deploy/environment-compatibility/#tested-dbmss)
APIM - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/reference/product-compatibility/
