### ISSUE TITLE
Compatible workflow packs to be deployed in Enterprise Integrator 

### ISSUE THREAD

**Issue by himasha** [wso2/product-apim#1333]
Regarding issue https://github.com/wso2/product-ei/issues/78, due to the file structure changes in business-process component of EI, need workflow packs that are created to fit the updated file path.

**Comment by tharikaGitHub** [comment]
For Application Registration Workflow for example, the endpoint reference specified in **ApplicationRegistrationWorkflowProcess_1.0.0/deploy.xml** should be modified to 

`endpointReference="**./../../../../conf/epr/RegistrationService.epr**"`

instead of 

`endpointReference="./../../../../repository/conf/epr/RegistrationService.epr" `

**Comment by chamilaadhi** [comment]
Instructions are provided in the official document on how to set this up using EI https://docs.wso2.com/display/AM260/Adding+an+Application+Creation+Workflow
