### ISSUE TITLE
API Alerts dashboard - Drop down for tier crossing doesn't work

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-apim#1692]
**Description:**
The drop down for "tier crossing" alert is not working in the Alerts dashboard. Please check all other drop down items too.

**Suggested Labels:**
analytics, alerts, dashboard

**Suggested Assignees:**

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Generate some alerts and click on the drop down for tier crossing alerts.

**Related Issues:**

**Comment by fazlan-nazeem** [comment]
This issue seems to be because we have not indexed some fields properly in some alert tables. https://github.com/wso2/analytics-apim/blob/master/features/org.wso2.analytics.apim.feature/src/main/capp/Eventstores/org_wso2_analytics_apim_store_tierLimitHitting_1.0.0/org_wso2_analytics_apim_tierLimitHittingAlert.xml#L62

**Comment by dewmini** [comment]
Fixed with https://github.com/wso2/analytics-apim/commit/1314519016de5c9c73ebeba25ac134b4bf62dba8
