### ISSUE TITLE
[AMHACK] Unable to edit an API which is in published state without subscribers

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1718]
**Description:**
Unable to edit an API (ex: add an image to the API) which is in a published state, when no subscriptions were made against this API.

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. API creator creates a API
2. API publisher publishes the API
3. API creator wants to change the image added to the API

**Observations**
1. Not allowed to select an image (can not edit the API)
![image](https://user-images.githubusercontent.com/14962228/33070968-c24d506c-cedf-11e7-8416-945de40be770.png)

**Expected Result**
Should be possible to edit the API as there are no subscriptions
If we do not allow to edit the APIs for a particular reason, it should have appeared as an error message or info message that it's not possible to edit the API (with a valid reason)

**Comment by tgtshanika** [comment]
This is the expected behavior by design. Following is the scenario implemented in API publisher design phase. 

1. API developer(create permissions) creates the API. He can only save the API
2. API business owner(publish permissions) review the API info and publish the API. Once the API is published, the business would own the API and the developers cannot make changes so that the edit capabilities are disabled.
3. If the developer wants to make changes, he/she has to create a new version of the API, make the required changes and publish that particular API. Or else, they have to demote it to created state, apply the changes and republish.
