### ISSUE TITLE
[AMHACK] Previously used APIM server hangs on start up

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1724]
**Description:**
Failed to start the APIM server (used to verify several carbon super and tenant scenarios and debug log is enabled from the carbon_console appender from the management console logging component). 

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Start the server

**Observations**
Observed the following warning logs in the terminal
```
[2017-11-21 21:48:13,189]  INFO -  Using a shared selector for servlet write/read {org.apache.tomcat.util.net.NioSelectorPool}
[2017-11-21 21:48:13,231]  INFO -  Using a shared selector for servlet write/read {org.apache.tomcat.util.net.NioSelectorPool}

```

[carbonlogs.zip](https://github.com/wso2/product-apim/files/1494587/carbonlogs.zip)

**Comment by chamilaadhi** [comment]
Was this server started at anytime? (wanted to see whether it eventually started). the provided information is not enough to narrow down this issue. I tried to reproduce it with the description you provided but there wasn't any such thing happening. So please take at least a thread dump during this issue so that we could analyze it.
