### ISSUE TITLE
[AMHACK] Custom attributes added to the subscription tier does not appear in the API subscription page

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1747]
**Description:**
Customer attributes added to the Subscription tier is not available in the API Store's API subscription page as explained in [1]

[1] https://docs.wso2.com/display/AM210/Adding+New+Throttling+Policies#AddingNewThrottlingPolicies-Addinganewsubscription-levelthrottlingtier

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Oracle 15.10
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre-Requisits
1. Few APIs should exist in the API store

**Steps to reproduce:**
1. Log in to API admin console 
2. Add a subscription tier with custom attributes
3. Log in to API store go to API subscription page as mentioned in [1]
[1] https://docs.wso2.com/display/AM210/Adding+New+Throttling+Policies#AddingNewThrottlingPolicies-Addinganewsubscription-levelthrottlingtier

![screenshot from 2017-11-23 17-41-18](https://user-images.githubusercontent.com/14962228/33172314-a3182036-d075-11e7-8242-56313f966524.png)

**Observations**
1. Could not found the added attributes for the tier in the subscription page
![screenshot from 2017-11-23 17-41-24](https://user-images.githubusercontent.com/14962228/33172309-a0561d8a-d075-11e7-8770-aa14e5fd9c60.png)

**Comment by sambaheerathan** [comment]
Custom attributes are there to display some properties of tiers when the users are trying to write some custom implementations such as API monetization. Since these are custom implementations and the person who implements the extension decides where to display the attributes, we are not showing them in the Store UI.

**Comment by sashikamw** [comment]
As per the doc "**Custom attribute values are displayed as key value pairs on the API Store's API subscription page**" if it's only applicable to the custom implementation this should be documented properly, if not a user might get confused with the wording. 

![screenshot from 2018-01-03 12-12-58](https://user-images.githubusercontent.com/14962228/34511190-a60d139e-f07f-11e7-86c4-317596598588.png)

**Comment by sambaheerathan** [comment]
I have created a doc JIRA[1] to update the doc. The attributes are not returned to the frontend and this has to be fixed in [2]
[1] https://wso2.org/jira/browse/DOCUMENTATION-7541
[2] https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java#L1941
