### ISSUE TITLE
[AMHACK] No validation provided when multiple external stores added with same id

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1923]
**Description:**
[AMHACK] No validation provided when multiple external stores added with the same id

**Suggested Labels:**
Bug
APIM carbon console

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Go to Management console -> Registry resource
2. Add 2 external stores with same id as given below and save 
```
<ExternalAPIStores>

	<!--Configuration to set the store URL of the current running APIM deployment. 
	APIs published to external stores will be redirected to this URL-->
	
	<StoreURL>http://localhost:9763/store</StoreURL>

        <ExternalAPIStore id="Store2" type="wso2" className="org.wso2.carbon.apimgt.impl.publishers.WSO2APIPublisher">
            <DisplayName>UK Store</DisplayName>
            <Endpoint>http://localhost:9764/store</Endpoint>
            <Username>admin</Username>
            <Password>admin</Password>
        </ExternalAPIStore>

       <ExternalAPIStore id="Store2" type="wso2" className="org.wso2.carbon.apimgt.impl.publishers.WSO2APIPublisher">
            <DisplayName>US Store</DisplayName>
            <Endpoint>http://localhost:9765/store</Endpoint>
            <Username>admin</Username>
            <Password>admin</Password>
        </ExternalAPIStore>
	

</ExternalAPIStores>

```

**Observations**
1. Not allowed to save the registry resource
2. No UI validation provided 
3. No backend validation provided

**Comment by msm1992** [comment]
I followed the mentioned steps and below are the observations.

- Registry resource can be saved but in APIM only one external store is configured in reality.
- No UI validation or backend validation is given.

However this is a limitation and cannot be fixed from APIM side. Relevant code segment comes from carbon-registry repo and it checks whether the content is a valid xml only.
As far as the entered text is a valid xml, registry resource can be saved. Resource specific validations cannot be introduced here because this is a generic component and is used in other places as well.

**Comment by dewmini** [comment]
Closing the issue as per above comment.
