### ISSUE TITLE
[AMHACK][Billing Sample] Need to log in from an incognito window to create a billing plan

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1925]
**Description:**
Unable to log in to billing engine sample, (step 7 "Test the system") to create a billing plan due to session issues

[1] https://docs.wso2.com/display/AM210/Enabling+Monetization+of+APIs

**Suggested Labels:**
Bug
APIM Monetization - billing engine sample

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)
Tomcat version - apache-tomcat-7.0.68 / deploy in APIM server as a web app

**Steps to reproduce:**
1. Configure the environment as given in [1]
2. Log in to billing engine as mentioned in "Test the system" step 6

[1] https://docs.wso2.com/display/AM210/Enabling+Monetization+of+APIs

**Observations**
1. Failed to log in to billing engine frome the same browser. Even with correct username and password, failed to login. And it will redirect to the 'Sign up' page.

2. If access the billing engine sample accessed via a "Incognito Window" I was able to log in using the created user.

**Comment by chamilaadhi** [comment]
Hi,
This billing webapp is provided as a sample and there could be limitations and issues with this sample. (as a result, this sample is removed from the AM 2.6.0 documentations as well since it is not a production-ready sample)

In APIM 3.0.0 we have provided an out of the box configuration support with an actually billing engine. You could follow this feature in https://github.com/wso2/product-apim/issues/4680
