### ISSUE TITLE
[AMHACK] Application status will remain ON_HOLD if a user logs in to billing application via an existing user

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1928]
**Description:**
Application status will remain ON_HOLD if a user logs in to billing application via an existing user

[1] https://docs.wso2.com/display/AM210/Enabling+Monetization+of+APIs

**Suggested Labels:**
Bug
APIM Monetization - billing engine sample

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)
Tomcat version - apache-tomcat-7.0.68 / deploy in APIM server as a web app

**Steps to reproduce:**
1. Configure the environment as given in [1]
2. Create a new application and subscribe to that application using the sample API
3. Log in with an existing user to the billing system once redirected to the billing engine login page

[1] https://docs.wso2.com/display/AM210/Enabling+Monetization+of+APIs

**Observations**
1. It will redirect to the Account Homepage
2. Application status will remain in ON_HOLD state and will not be able to recover 

![screenshot from 2017-12-03 00-08-38](https://user-images.githubusercontent.com/14962228/33518645-4d605dc0-d7be-11e7-9dff-011bb26ec10c.png)

![screenshot from 2017-12-03 00-10-41](https://user-images.githubusercontent.com/14962228/33518651-80edca10-d7be-11e7-9af4-9ecd22597315.png)

**Comment by chamilaadhi** [comment]
Hi,
This billing webapp is provided as a sample and there could be limitations and issues with this sample. (as a result, this sample is removed from the AM 2.6.0 documentations as well since it is not a production-ready sample)

In APIM 3.0.0 we have provided an out of the box configuration support with an actually billing engine. You could follow this feature in https://github.com/wso2/product-apim/issues/4680
