### ISSUE TITLE
Do we plan to provide a mechanism to start all profiles at once for evaluation purposes? 

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-apim#2010]
**Description:**
I have to start 4 profiles to get an initial sample going? 
If I am a developer trying to evaluate, or get a local setup going in whuck time, why do I need 4 terminals and 4 commands? Can we wrap this up to help evaluation and getting started efforts? 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by malinthaprasan** [comment]
Hi @samisawso2 

Currently, the problem is we are depending on some servers which need to be provided externally (IS and activeMQ). We will be providing a new runtime (key-manager) with essential authorization/authentication functionality which can be used instead of IS for primary APIM tasks. APIM need to [support Key manager by default](https://github.com/wso2/product-apim/issues/2031). We will also [embed MB4 ](https://github.com/wso2/product-apim/issues/1845) such that we don't need to provide a separate broker. We will be providing a single script to start all the required servers once the above tasks are done.

**Comment by samisawso2** [comment]
So you think this is a valid requirement for evaluation purposes

**Comment by samisawso2** [comment]
So you think that this is a valid requirement for evaluation?

It is OK to take time and get this right. As long as it is done right for
first time users.
Need to double check with the installation experience efforts as well.

**Comment by malinthaprasan** [comment]
Yes Samisa, this is a valid requirement for evaluation. Once the above few blocking issues are resolved, I believe we should be able to provide a way start all the components from a single script.

The installation efforts will also be much less compared to the current version once we could embed required IS features(key manager) and MB within API Manager. After that, first-time users can evaluate features at a significant level only using the API Manager pack. But to evaluate a bit more advanced IS specific features such as SSO they may have to configure IS 5.4.0.
