### ISSUE TITLE
API Development: document does not describe the steps the user needs to do to get the sample working

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2140]
In [1] the business use case, business story is there, but there is no clear steps in how to achieve this sample. This is very crucial for any person who is trying this out. So rather than having some images, please structure the document so that it explains the use case, how its achieved using api manager with steps and images.

[1] https://docs.wso2.com/display/AM2xx/Ownership%2C+permission+and+collaborative+API+development+-+Documentation

**Comment by chamindias** [comment]
The relevant information is already included under "How this business scenario can be achieved Using WSO2 API Manager?" in [Ownership, permission and collaborative API development - Sample Documentation](https://docs.wso2.com/display/AM2xx/Ownership%2C+permission+and+collaborative+API+development+-+Sample+Documentation). Hence resolving.

**Comment by erandidesilva** [comment]
@chamindias 
If I am the user trying to get this implemented, then a guide in how to get it done would be more helpful. But the current document only contains the high level description. If you place yourself in a user trying to get POC working will this information in current documentation enough?

**Comment by chamindias** [comment]
Let me explain the intention of these sample scenarios. Those are for demonstrating business use cases (indeed, those are high level use cases). We are not guiding the reader to carry out step-by-step technical instructions as the official technical documentation contains step-by-step instructions.  However, as an improvement, we have pointed to relevant sections in the the official documents within sample scenarios. Otherwise there will be so much of duplicate content (i.e - in the technical docs and sample scenarios). Hope that is clear.

Thanks.
