### ISSUE TITLE
Rest API: Introduce parameter based resource definition when creating an api

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2266]
Currently according to [1] a full swagger definition has to be sent via the payload to create resource etc... It would be great if parameters can be introduced for the external developer to populate and the rest be through our code for ease of use

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APICollection#apisPost

**Comment by chamindias** [comment]
To create an API, yes, we need to send the full definition because we are adding an API from the scratch. We can use the [update swagger definition operation](https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APIIndividual#apisApiIdSwaggerPut) whenever there is a need to update the swagger definition only.
