### ISSUE TITLE
Cannot be deleted the application which created with name having special characters

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2323]
**Description:**
As $subject when click on delete icon of an application which has been created with name appended some special characters, an API store error pops up. See attached.

**Suggested Labels:**
APIM2.2.0
Type/bug
Priority/normal
Sevirity/critical

**Affected Product Version:**
2.1.0-update5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Add app with name like (e.g. TomsApp${counterValue})
![wrongapp](https://user-images.githubusercontent.com/15671620/34766345-19c0207a-f61a-11e7-919b-23e1213be156.jpeg)

- List and delete the above app
![storeerror](https://user-images.githubusercontent.com/15671620/34766340-14933fec-f61a-11e7-90b4-b00b1bcc522c.jpeg)

- Click on OK won't get delete the app
Note that there were no carbon log for this issue.

**Comment by msm1992** [comment]
API Manager does not allow application names with special characters. Adding such application names was already restricted through UI but it was still possible to add such applications through Store REST API. This issue is now fixed with [1]. 
The problem reported here is due to application name validation that occurs while removing application; to be more precise an application name that was not validated during creation is being validated at deletion. 

[1]. https://github.com/wso2/carbon-apimgt/pull/5046

**Comment by bhathiya** [comment]
Closing as this is fixed.
