### ISSUE TITLE
Support for http 2.0

### ISSUE THREAD

**Issue by samtonyclarke** [wso2/product-apim#2410]
From what I can tell APIM doesn't have support for http 2.0 in any version. If that is correct is their any plans to add support?

**Comment by isharac** [comment]
Fixed in micro gateway.

We have added the HTTP 2.0 support in our product microgateway with the below PRs.
https://github.com/wso2/product-microgateway/pull/285
https://github.com/wso2/product-microgateway/pull/286

**WSO2 API Manager Microgateway**
The Microgateway provides the capability to create specialized gateway distribution (Microgateway distributions) where only a single API or a group of APIs are included. Once a Microgateway distribution is started, it will start serving those specific API(s) right away.

For more information on wso2 micro gateway please refer https://github.com/wso2/product-microgateway

**Comment by SiluniPathirana** [comment]
WSO2 API Manager does not support  HTTP/2 and only the micro-gateway does. Since HTTP/2 support is a valuable feature to have in the APIM product,

Will it be possible to use the Netty-based HTTP transport which is used in Ballerina to support HTTP/2?

**Comment by mahtahassanpour** [comment]
> WSO2 API Manager does not support HTTP/2 and only the micro-gateway does. Since HTTP/2 support is a valuable feature to have in the APIM product,
> 
> Will it be possible to use the Netty-based HTTP transport which is used in Ballerina to support HTTP/2?

Isn't it (HTTP2) supported in WSO2 ei either?
