### ISSUE TITLE
Providing endpoint url when creating API requires giving both sandbox and production endpoints

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2590]
**Description:**
- When creating an API and providing endpoint URL, REST API requires having both sandbox and production endpoints defined.

- IMHO user should be able to create an API with only production or sandbox endpoint defined.

**Affected Product Version:**

- APIM 3.0.0-m14

**Steps to reproduce:**

- Invoke /apis POST with only production or sandbox endpoint definitions

**Comment by tgtshanika** [comment]
This is fixed in APIM 3.0.0 m35. As per the new UI design, a user can create an API with a prod/sandbox endpoint or even without specifying an endpoint URL.
<img width="782" alt="Screen Shot 2019-09-19 at 12 26 25 PM" src="https://user-images.githubusercontent.com/4471756/65220636-ba9aa980-dad8-11e9-9a09-7fd3cf2914f2.png">
