### ISSUE TITLE
Invalid API count is displayed on the Store in apim cluster

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2650]
**Description:**
Invalid API count is displayed on the Store in apim cluster pattern-6. There are only 2 APIs but it displays as 17

![image](https://user-images.githubusercontent.com/7115693/35674261-18ce627e-076a-11e8-8b94-2d80053b747c.png)

**Affected Product Version:**
APIM2.1.0 WUM

**OS, DB, other environment details and versions:**    
Ubuntu, JDK1.8, MySQL

**Steps to reproduce:**
Repeated below steps.
Create and publish an API >> Subscribe to the API >> Invoke >> Delete
Followed same steps using same API name for each time.

**Comment by this** [comment]
This issue can be reproduced in a non-clustered environment as well. Here are more details.

#### Affected Product Versions:
- APIM-2.x series 

#### Steps to reproduce
1. Start a APIM setup with default configuration.
2. Create more than 12 (since default pagination size is 12) different APIs (different names).
3. Visit https://localhost:9443/store/?page=1 Store page and identify an API that is visible in the 1st page.
4. Goto Publisher and create a new version of that API. The publish it.
5. Refresh the https://localhost:9443/store/?page=1 Store page and you will notice only 11 APIs are visible.
![image](https://user-images.githubusercontent.com/11549922/48127586-18037e80-e2aa-11e8-9c4b-cc98dbef7367.png)

#### Root cause of this problem can be summarize as follows,
- The Jaggery layer requests 0-12 page (12 APIs) from the backend.
- The backend APIM layer query for 0-12 page from the registry and registry returns 12 artifacts.
- Then APIM layer (`APIConsumerImpl` class) filter out multiple versions of the same API if `<DisplayMultipleVersions>` configuration is set to `false` (which is the default value). This reduce the APIs count to <12.
- Then the Jaggery layer renders the UI assuming there are 12 APIs, which is inaccurate.

#### Possible workarounds:
- Setting `<DisplayMultipleVersions>` to `true` in the `api-manager.xml` file so that multiples versions are shown in the UI.

**Comment by HiranyaKavishani** [comment]
Cannot reproduced in master
