### ISSUE TITLE
[UX][Store] Production keys access token title shows as "Generate a Test Access Token"

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2950]
**Description:**
***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Aesthetic and minimalist design - Is the system contains information which is relevant and needed? (no irrelevant or rarely needed info)

***Related task:***
Subscribe to an application

***Issue & Solution:***
Key generated view of Production keys shows a title as "Generate a Test Access Token". Since this key is used for production the title needs to rename to "Generate a Access Token".
![accesstoken](https://user-images.githubusercontent.com/9837443/37191902-77ecff56-2388-11e8-8fa4-2efec4b29b34.png)

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0

**Comment by tmkasun** [comment]
In here the word `Production` has used to indicate the API endpoint that the request will be routed. That doesn't mean that you have to generate a production access token from here to use in production and generate a sandbox key otherwise.
The generate key functionality is provided here to **test** API using either production or sandbox access tokens.

So IMO, the usage of the word `Test` in the context of `Generate a Test Access Token` is valid here.

@chanaka3d , @tgtshanika , @bhathiya any comment on this ? Because we have implemented the test key UI in 3.x with the same notion

**Comment by bhathiya** [comment]
Yes, the key generated here is not supposed to be used in real production. It's used to "Test" the production endpoint.
