### ISSUE TITLE
user info displays only username eventhough email is configured as a mandatory claim

### ISSUE THREAD

**Issue by ushanib** [wso2/product-apim#3024]
user info displays only username eventhough email is configured as a mandatory claim.

Folowed the steps given in [1]

curl -k -v -H "Authorization: Bearer <ACCESS_TOKEN>" https://<GATEWAY_HOSTNAME>:<PORT>/userinfo

 curl -k -v -H "Authorization: Bearer 473ac186-9b44-32d9-bf67-78b3bac86dc4" https://localhost:8243/userinfo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8243 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=localhost,O=WSO2,L=Mountain View,ST=CA,C=US
* 	start date: Jul 19 06:52:51 2017 GMT
* 	expire date: Jul 17 06:52:51 2027 GMT
* 	common name: localhost
* 	issuer: CN=localhost,O=WSO2,L=Mountain View,ST=CA,C=US
> GET /userinfo HTTP/1.1
> Host: localhost:8243
> User-Agent: curl/7.43.0
> Accept: */*
> Authorization: Bearer 473ac186-9b44-32d9-bf67-78b3bac86dc4
> 
< HTTP/1.1 200 OK
< X-Frame-Options: DENY
< Cache-Control: no-store
< X-Content-Type-Options: nosniff
< Pragma: no-cache
< X-XSS-Protection: 1; mode=block
< Content-Type: application/json
< Date: Tue, 13 Mar 2018 13:12:22 GMT
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"sub":"chalitha"}[

![screenshot from 2018-03-13 18-44-46](https://user-images.githubusercontent.com/12966170/37343776-99b29038-26ee-11e8-843a-3422f8cff2f4.png)

Have I missed anything else?

[1] https://docs.wso2.com/display/AM2xx/Obtaining+User+Profile+Information+with+OpenID+Connect#817256be89214ff897ae144c03301893

**Comment by tharindu1st** [comment]
Hi @ushanib ,

This is the default behavior if you didn't add requested claims in service provider you will only get subject claim. In order to add claims need to get you have to add it as below.

1. Go to the management console
2. Navigate to Service provider list
3. Go to the generated service provider and add as below way.
![screenshot from 2018-03-13 20-05-27](https://user-images.githubusercontent.com/6345931/37348525-4873318a-26fa-11e8-88c2-0cac41a0c108.png)

**Comment by ushanib** [comment]
HI Tharindu,

I cannot see any Service provider created for a user who is registered via sign up. Can you please confirm whether I miss any step?

Thanks

**Comment by tgtshanika** [comment]
Hi Ushani,

If an OAuth token has been generated in order to access the userinfo endpoint, a corresponding Service provider should be created. Subscriber user does not have permission to view/edit service providers. Please grant the relevant permissions and try to add the claims as described in previous comment
