### ISSUE TITLE
[Store][UX] User cannot change the application subscription tier of an API

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3134]
**Description:**
User cannot change the application subscription tier of an API after subscribing to an application.
![screenshot-subscriptions](https://user-images.githubusercontent.com/9837443/38071128-2e75ec24-333d-11e8-8271-928b6f4e2814.png)

User needs to unsubscribe and subscribe again to change the tier.

**Suggested Labels:**
UX, Bug

**Affected Product Version:**
2.2.0

**Comment by tgtshanika** [comment]
This is the expected behavior by design. The API consumers are subscribing an API for a given business plan and if there is a requirement of changing the current business plan, they need to unsubscribe from the existing plan and make a new subscription to the required plan. Changing the business plan on fly, breaks the subscription policies, monetization flow. Hence, the consumers are not allowed to change the plan, once the subscription is already made.
