### ISSUE TITLE
Duplicate records are added to the IDN_OAUTH2_SCOPE 

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#3190]
**Description:**
Duplicate records are added to the IDN_OAUTH2_SCOPE table when we save an API on design tab. 

Steps.
1.Design a new API and engage the scopes with the resource paths
2.Check the IDN_OAUTH2_SCOPE table
![idn_oauth2_scope](https://user-images.githubusercontent.com/6552100/38546270-d011130c-3cc9-11e8-87b7-51206ee1923a.png)

**Comment by shavantha** [comment]
Doc Impact :N/A

**Comment by jpvadell** [comment]
I am using 2.1, 2.6 and 3.0 Beta and can replicate the same behavior.
The amount of duplicated columns is the same than the amount of resources you assign with a scope.
I have 43 resources assigned to the same scope. So...
the table **idn_oauth2_scope** has 43 rows with the same scope.
the **idn_oauth2_resource_scope** has 43 resources but all of them assigned to the last scope_id.
and the table **idn_oauth2_access_token_scope** has the token_id and the token_scope (is the name of the scope...) and tenant_id.
This is very strange...  because I have 43 duplicated scopes... but assigned to the last scope_id... and then, the token how validates the token_scope if I have 43 tokens with the same scope name?

**Comment by kavishkafernando** [comment]
This issue has been fixed in APIM-2.6.0 according to : #https://github.com/wso2/product-apim/issues/3201#issuecomment-529512973
