### ISSUE TITLE
API Console wrong gateway

### ISSUE THREAD

**Issue by ThiagoMenezesAbreu** [wso2/product-apim#3204]
**Description:**
Even with the definition  of the gateway URL in "<GatewayEndpoint>" the API Console in the API Store set the wrong api gateway url. Also, the wrong url is the url foi ate API Store itself.

After hours I found that problem occur only when you set only one URL address in GatewayEndpoint.
The workaround is set the same url twice, like: "<GatewayEndpoint>https://api.xyz,https://api.xyz</GatewayEndpoint>"

Note: the API is marked to HTTP and HTTPS on publisher.

**Suggested Labels:**
2.2.0

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    
2.2.0

**Steps to reproduce:**
- Set a UNIQUE url in "<GatewayEndpoint>" of an gateway in api-manager.xml
- Deploy an API in publisher
- Try to use it in API Console on Store
- Notice the endpoint URL was the URL of the API-Store itself.

**Comment by tgtshanika** [comment]
It seems like you haven't configured the https endpoint of the gateway under GatewayURL config in api-manager.xml. The API console uses the **https** endpoint of the gateway when originating the API request to the selected gateway environment(Due to cross-origin access). If the https endpoint is missing, the store host:port is used to construct the API endpoint. Hence this is not a bug, but the expected behavior.
