### ISSUE TITLE
Fix validation issues with mediation script from the Publisher UI

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#3260]
**Description:**
Currently, the UI validation in the Prototyped APIs inline mediation tab marks the below code as invalid js code even though it is valid for js engine in synapse.

`mc.setPayloadXML(<note><foo>bar</foo></note>);`

![image](https://user-images.githubusercontent.com/1591316/39623021-ee151862-4fb1-11e8-9e61-73c5bdc0c686.png)

Need to remove improper validations.

**Affected Product Version:**
API Manager 2.1.0, API Manager 2.2.0

**Comment by tmkasun** [comment]
In current master branch, We don't have any syntax highlighting or error validations in the prototype code editor, Hence this issue is still valid for 3.x series as well

![image](https://user-images.githubusercontent.com/3313885/96439368-58a0fc00-1224-11eb-91ed-0bc2001c3908.png)

we need to fix this.
