### ISSUE TITLE
Adding a note about importing the certificate of the API Manager into client-truststore into BPS in Managing Workflow Extensions related documentations

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-apim#3337]
**Description:**
We need to add below note for every workflow extensions under the documentation [1].

Note
When enabling the workflow features make sure to import the certificate of the API Manager into client-truststore which is located inside the <BPS_HOME>/repository/resources/security directory. 

[1]. https://docs.wso2.com/display/AM220/Managing+Workflow+Extensions

**Suggested Labels:**
APIM 
Type/Improvment

**Affected Product Version:**
APIM 2.2.0

**Comment by taniamahanama** [comment]
Added the note in the following:
https://docs.wso2.com/display/AM220/Adding+an+Application+Creation+Workflow
https://docs.wso2.com/display/AM220/Adding+an+Application+Registration+Workflow
https://docs.wso2.com/display/AM220/Adding+an+API+Subscription+Workflow
https://docs.wso2.com/display/AM220/Adding+a+User+Signup+Workflow
https://docs.wso2.com/display/AM220/Adding+an+API+State+Change+Workflow

**Comment by taniamahanama** [comment]
Also fixed in:
https://docs.wso2.com/display/AM2xx/Adding+an+Application+Creation+Workflow
https://docs.wso2.com/display/AM2xx/Adding+an+Application+Registration+Workflow
https://docs.wso2.com/display/AM2xx/Adding+an+API+Subscription+Workflow
https://docs.wso2.com/display/AM2xx/Adding+a+User+Signup+Workflow
https://docs.wso2.com/display/AM2xx/Adding+an+API+State+Change+Workflow
