### ISSUE TITLE
Localization error in Google Chrome

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-apim#3660]
**Description:**
When trying to localize the API Store, according to the doc[1],
When current browser language is set to Spanish it leads i18n to define current Locale as English.

Here the client side (js) correctly pick the i18nResources_es.json file while the server side (jaggery) picks locale_default.json instead of locale_es.json.

**Affected Product Version:**
APIM 2.5.0

**OS, DB, other environment details and versions:**    
Ubuntu 16.04 os  and Chrome browser

**Steps to reproduce:**
Try to localize the API Store, according to the doc[1],
Set the current browser language to Spanish
But add the English to the top of the chrome language list.

[1] https://docs.wso2.com/display/AM210/Adding+Internationalization+and+Localization

**Comment by SwatiNEC** [comment]
Hi

As per my analysis, server side (jaggery) picks correct locale file on the basis of the current browser language. But locale_es.json file doesn't contain all the keys so it is picking up the content from locale_default.json for the keys which are not defined in locale_es.json file. So for solving this issue, locale_es.json needs to be updated for all the keys defined in locale_default.json file.

**Comment by TanyaM** [comment]
Store implementation picks the locale that the client will accept content in, based on the Accept-Language header. If the client (browser in this case) request doesn't provide an Accept-Language header,then use the default locale for the server.
Therefore if the user keeps English at the top of the language list in the browser even though Spanish is in the list, Accept Language header will look like below.
**Accept-Language: en,es;q=0.9**
So the user will be served with the English language in the browser.

Therefore if the user needs to see the store interface in Spanish, he needs to bring the Spanish to the top of the list in chrome settings.

But as @SwatiNEC explains above, there is an issue with the spanish locale files ( locale_es.json and i18nResources_es.json ) that is shipped OOTB with the pack, where it doesn't contain all the keys that is there in the default locale files. So when there is a missing key it will fall back to the default locale file. Since the default locale file is written for English language, user will see the interface in English.

We will update the Spanish and other locale files that we ship with the product OOTB to contain all keys.

**Comment by TanyaM** [comment]
Fixed with above PR.

**Comment by isharac** [comment]
Missing spanish translations added.
https://github.com/wso2/carbon-apimgt/pull/6027/commits/bd0c8e9c22ef540c77726b6d6d013859e5592236
