### ISSUE TITLE
[API Store][API Publisher]When the user account is locked, provide a suitable error message other than saying the provided credentials are invalid. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#3781]
**Description:**
Once a user account is locked, the error message displayed in the UI is **'Error! Login failed. Please recheck the username and password and try again'** which may mislead the user. In the carbon log, it displays as below. 

```
[2018-09-28 10:49:19,184]  WARN - IdentityMgtEventListener User account is locked for user : uyanage. cannot login until the account is unlocked 
[2018-09-28 10:49:19,185] ERROR - AuthenticationAdmin System error while Authenticating/Authorizing User : 17003 User account is locked for user : uyanage. cannot login until the account is unlocked 
```

It would increase the usability if we propagate the same message to the user or a suitable general message such as '**Your account is locked**' at the time the user account gets locked and the user is unable to login.

**Suggested Labels:**
Type/New Feature
Severity/Major
Priority/High
Affected/2.5.0

**Affected Product Version:**
2.5.0

**Steps to reproduce:**
1. Setup account locking as in [1] 
2. Create a user, user1. 
3. Try to login to API Store with invalid credentials for user1. Do three attempts. 
4. In the 4th attempt, provide correct credentials. 

Still, you get the error message as below which misleads user since the user has provided the correct credentials but actually the account is locked. 
![accountlock](https://user-images.githubusercontent.com/31693103/46190046-759dc600-c30f-11e8-9d42-86c17867a538.png)

[1] - https://docs.wso2.com/display/AM250/Identity+Management+for+the+API+Store#IdentityManagementfortheAPIStore-Accountlockingbyfailedloginattempts

**Comment by pravindeok** [comment]
Thanks, do we have ETA on this feature request? please let me know if it is available via wum update. thanks.

**Comment by TanyaM** [comment]
In-order to invoke the login flow, we use the  stub [1] of AuthenticationAdmin service [2] provided by carbon kernel. And the functionality provided by kernel only returns a boolean indicating whether the login is successful or not. It doesn't return any other info as invalid credentials, account locked, disabled etc. 

Changing the admin service method to return this information will cause an api change and will break other components using the same admin service.
If we are to implement this, it will be a drastic change to number of components.

If one needs this information, a workaround would be to enable sso for the store application and enable the setting described at [3] so that IDP component will send the required information to the application side.

On a side note, if the account is locked after defined failed attempts, it is a security vulnerability to provide the message that account is locked once the user provides the correct credentials. Because a malicious use can do a brute force attack and identify the correct password once he gets the account locked message. 

Ideally expected scenario would be to show the "account locked" message for all different combinations of username and password ( either correct credentials or not) after defined number of failed attempts.

[1] https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java#L681
[2] https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.core.services/src/main/java/org/wso2/carbon/core/services/authentication/AuthenticationAdmin.java#L61 
[3] https://docs.wso2.com/display/IS550/Customizing+Authentication+Error+Messages
