### ISSUE TITLE
Token API should not timeout within 30 seconds.

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/product-apim#3912]
**Description:**
As of now token API get timed out within 60 seconds if oauth app does not respond. Some of the users need  default behavior to never suspend after timeout. As of now we can modify deployment automation tool or change shared file system one time. But when it comes to micro gateway deployments we cannot always do that as user starts with default pack. So suggestion was to add this to default product.

**Important:**
We should never introduce this change during update or minor release. Reason is we do have users who parse token API xml assuming current structure(elements, xpaths etc). If we change in update or minor release it may get break. If we do this with major release those users have time to identify and fix issues with that.

**Comment by amilam** [comment]
Concern is not timing out. IMO, it is ok to timeout after the some default time. Real concern is, the endpoint in the token api getting suspended for 30 seconds if the endpoint was not reachable due to some reason. That is what I want to remove. If the endpoint of token api failed, when the next request comes, it should try again to reach the endpoint rather than keeping it suspended.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if this requirement is still needed to be implemented with the latest version.
