### ISSUE TITLE
HTTP 2.0 Support in API Manager

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim#3936]
**Description:**
Enable HTTP 2.0 support in API Manager.

**Comment by isharac** [comment]
Fixed in micro gateway.

We have added the HTTP 2.0 support in our product microgateway.
https://github.com/wso2/product-microgateway/pull/285
https://github.com/wso2/product-microgateway/pull/286

**WSO2 API Manager Microgateway**

The Microgateway provides the capability to create specialized gateway distribution (Microgateway distributions) where only a single API or a group of APIs are included. Once a Microgateway distribution is started, it will start serving those specific API(s) right away.

For more information on wso2 micro gateway please refer https://github.com/wso2/product-microgateway
