### ISSUE TITLE
Missing Primary Keys/Unique Indexes in APIM tables

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-apim#4044]
In order to have database replication, should have a primary key or a unique index in each table. Following tables doesn't have any such constraints.

1. IDN_OAUTH2_SCOPE_BINDING
2. AM_API_SCOPES 
3. IDN_OAUTH2_ACCESS_TOKEN_AUDIT

**Comment by isharac** [comment]
AM_API_SCOPES table is removed since API 3.2.0 with the introduction of shared scopes feature. Instead it uses AM_SCOPE and AM_SHARED_SCOPE tables. These tables have primary keys defined.
IDN_OAUTH2_SCOPE_BINDING and IDN_OAUTH2_ACCESS_TOKEN_AUDIT addressed in https://github.com/wso2/product-apim/issues/9505
