### ISSUE TITLE
No Validation for the Description field in Registering Applications

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#4098]
**Description:**
When Creating APIs in API publisher we have a validation for Description field with Maximum 20000 characters. But in Registering STORE applications we don't have a validation for Description field max character count. Suggest to add a validation and mention it below the input field as a improvement

**Suggested Labels:**
Type/product scenario
Type/UX
Type/Improvement
Severity/Major
version/2.6

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.6.0

**Comment by nimanthag** [comment]
Hi @ShanikaWickramasinghe ,
Description field value in application is stored in AM_APPLICATION table. According to the DB script 
Refer below
> CREATE TABLE IF NOT EXISTS AM_APPLICATION (
>     APPLICATION_ID INTEGER AUTO_INCREMENT,
>     NAME VARCHAR(100),
>     SUBSCRIBER_ID INTEGER,
>     APPLICATION_TIER VARCHAR(50) DEFAULT 'Unlimited',
>     CALLBACK_URL VARCHAR(512),
>     **DESCRIPTION VARCHAR(512**),
>     APPLICATION_STATUS VARCHAR(50) DEFAULT 'APPROVED',
>     GROUP_ID VARCHAR(100),
>     CREATED_BY VARCHAR(100),
>     CREATED_TIME TIMESTAMP,
>     UPDATED_BY VARCHAR(100),
>     UPDATED_TIME TIMESTAMP,
>     UUID VARCHAR(254),
>     TOKEN_TYPE VARCHAR(10),
>     FOREIGN KEY(SUBSCRIBER_ID) REFERENCES AM_SUBSCRIBER(SUBSCRIBER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
>     PRIMARY KEY(APPLICATION_ID),
>     UNIQUE (NAME,SUBSCRIBER_ID),
>     UNIQUE (UUID)
> )ENGINE INNODB;

maximum value that we can set is 512 not 20000. Hence we can add UI validation not to exceed 512. But their might be some customers those who have change this script for their customization. Hence  it is good to keep this behavior as it is. Otherwise fix for this may cause some migration issues.
