### ISSUE TITLE
[Publisher][UI] No proper UI validation for username field in endpoint auth credentials

### ISSUE THREAD

**Issue by malshaniS** [wso2/product-apim#4116]
**Description:**
There is no UI validation for username field in endpoint auth credentials. User can enter any character value[like special characters] for username. For an example: please refer below image. 

<img width="724" alt="screen shot 2019-01-02 at 1 48 42 pm" src="https://user-images.githubusercontent.com/40388545/50584373-2e3a4f00-0e95-11e9-9f36-5628087d9c7b.png">

For usernames, it is better to set a validation for characters. 

**Suggested Labels:**
product scenarios

**Suggested Assignees:**

**Affected Product Version:**
apim 2.6

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nimanthag** [comment]
Hi @malshaniS ,
These kinds of validations are added based on application restriction. For an example, if the custom application maintains a file based on this username it is good to have validation to avoid entering special characters since file creation will fail. But in APIM there is no such restriction. A user has flexibility add any name. Hence I don't think we need to add validation which is not good for performance as well.
