### ISSUE TITLE
Support analytics for oneway JMS apis

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#4546]
Currently GW not publish analytics events if API is created with JMS backend. Since JMS backend is configured as Async there is no response from the JMS backend. Hence no response, analytics response handler not get executed.

**Comment by nadeepoornima** [comment]
If the JMS backend has configured as Async(OUT_ONLY) manner, the BE will not send any response. As per our implementation, to publish the analytics, it should invoke the **APIMgtResponseHandler**. But due to not having a response when the JMS backend Async, we need to manually add that APIMgtResponseHandler to the "insequence" of the API(Normally the "APIMgtResponseHandler" is contained in the out sequence). 

In order to achieve that, you can edit the "velocity_template.xml" file(<AM_HOME>/repository/resources/api_templates) and add that required "APIMgtResponseHandler" when passing the OUT_ONLY property in the message context. 
In here we need to set some properties as well before invoking that "APIMgtResponseHandler". They need to set as the below values.
1. **BACKEND_LATENCY** = 0
2. **BACKEND_REQUEST_END_TIME** = 0
3. **HTTP_SC** = 202

**Steps**:
- Open the "velocity_template.xml" file and add the below filter to set those above-mentioned properties before selecting the production or sandbox endpoints. 
**Filter**
```xml
<filter source="$ctx:OUT_ONLY" regex="true">
        <then>
                <log level="full" message="test" value="hi"/>
                <property name="BACKEND_LATENCY" value="0" scope="axis2"/>
                <property name="BACKEND_REQUEST_END_TIME" value="0" scope="axis2"/>
                <property name="HTTP_SC" value="202" scope="axis2" type="INTEGER"/>
                <class name="org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtResponseHandler"/>

        </then>
        <else></else>
</filter>
```
**Where you need no that filter to the "velocity_template.xml" file?**(refer below part of the velocity_template.xml file)
``` xml
##############  define the filter based on environment type production only, sandbox only , hybrid ############

#if(($environmentType == 'sandbox') || ($environmentType =='hybrid' && !$endpoint_config.get("production_endpoints") ))
#set( $filterRegex = "SANDBOX" )
#else
#set( $filterRegex = "PRODUCTION" )
#end
#if($apiStatus != 'PROTOTYPED')
<filter source="$ctx:OUT_ONLY" regex="true">
        <then>
                <log level="full" message="test" value="hi"/>
                <property name="BACKEND_LATENCY" value="0" scope="axis2"/>
                <property name="BACKEND_REQUEST_END_TIME" value="0" scope="axis2"/>
                <property name="HTTP_SC" value="202" scope="axis2" type="INTEGER"/>
                <class name="org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtResponseHandler"/>

        </then>
        <else></else>
</filter>

<filter source="$ctx:AM_KEY_TYPE" regex="$filterRegex">
        <then>
````
- After adding the filter as above, then Save the "velocity_template.xml" file to deploy the changes to the environment.  
- Then you can republish the API which has already deployed, otherwise, when creating a new API with JMS backend as Async manner, those required properties and handler will add.
- Then invoke the APIs and see the analytics pages, then you could able to see the required analytics of particular API.
eg: ABC is my JMS BE api with Async manner
![LastAccessTime](https://user-images.githubusercontent.com/15210142/57070840-43fe3a80-6cf6-11e9-8b03-0c355379c722.png)
![APIUsage](https://user-images.githubusercontent.com/15210142/57070860-54aeb080-6cf6-11e9-8c07-2892b23c9100.png)
![usageByResourcePath](https://user-images.githubusercontent.com/15210142/57070874-62643600-6cf6-11e9-8386-7aa5ab9eea74.png)

**Comment by bhathiya** [comment]
Adding this to the product by default can introduce a small performance hit due to the new logic added. Therefore, this will not be added to the product. If someone needs this, they can manually do the change.
