### ISSUE TITLE
Need a way to validate access token validity period

### ISSUE THREAD

**Issue by JoneSabino** [wso2/product-apim#4693]
**Description:**
In the current version, AM allows the access token validity period to be overridden and does not provide a way to validate values sent by the user nor sent via API calls.

**Suggested Labels:**
APIM, 2.6.0

**Affected Product Version:**
APIM 2.6.0

**Steps to reproduce:**
Consider AccessTokenDefaultValidityPeriod and UserAccessTokenDefaultValidityPeriod with the default "3600" value.

send a request changing that value:
`curl -k -d "grant_type=client_credentials&validity_period=10000" -H ...`

response:
{"access_token":"1e4dd1e4-a55d-3124-a869-3eafcb0d0c64","scope":"am_application_scope default","token_type":"Bearer",**"expires_in":10000**}

There's no way to avoid/deny the default value to be changed.

**Comment by uvindra** [comment]
We have extended the default grant handler at APIM level to support the additional validity period parameter to give some flexibility to end users[1]. In order to restrict this functionality you can develop you own custom handler[2] that overrides this functionality.

[1] https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/ExtendedClientCredentialsGrantHandler.java#L48
https://docs.wso2.com/display/AM260/Writing+Custom+Grant+Types

[2] https://docs.wso2.com/display/AM260/Writing+Custom+Grant+Types
