### ISSUE TITLE
[Doc] Keep MB_STORE_DB default H2 configuration in Gateway Profile

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#5042]
We need to update the documentation [1] from 2.0 to 2.6, in the Gateway profile, as we need to keep the default h2 MB_STORE_DB configuration. Otherwise, the issue in https://github.com/wso2/product-apim/issues/4926 occurs in server startup when initializing broker components.

[1] https://docs.wso2.com/display/AM260/Understanding+the+Distributed+Deployment+of+WSO2+API-M

**Comment by Mariangela** [comment]
Updated an existing message in order to include this info. The following is the new note.

"Although the Gateway does not use the WSO2 API Manager database and the WSO2 Message Broker database, the default connections are required; therefore, do not remove the default configurations in the <API-M_HOME>/repository/conf/datasources/master-datasources.xml file. These connections should be your default database (H2 database)."


https://docs.wso2.com/display/AM300/Understanding+the+Distributed+Deployment+of+WSO2+API-M
https://docs.wso2.com/display/AM260/Understanding+the+Distributed+Deployment+of+WSO2+API-M
https://docs.wso2.com/display/AM250/Understanding+the+Distributed+Deployment+of+WSO2+API-M
https://docs.wso2.com/display/AM220/Understanding+the+Distributed+Deployment+of+WSO2+API-M
https://docs.wso2.com/display/AM210/Understanding+the+Distributed+Deployment+of+WSO2+API-M
https://docs.wso2.com/display/CLUSTER44x/Clustering+API+Manager+2.0.0
