### ISSUE TITLE
Publisher Resource listing doesn't show parameters with "ref" properly

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#5273]
**Step to Reproduce:**
Import a swagger with paths and "ref" parameters"
Eg:
```
      put: 
        summary: "Update swagger definition"
        description: "This operation can be used to update the swagger definition of an existing API. Swagger definition to be updated is passed as a form data parameter `apiDefinition`.\n"
        parameters: 
          - 
            $ref: "#/parameters/apiId"
          - 
            in: "formData"
            name: "apiDefinition"
            description: "Swagger definition of the API"
            type: "string"
            required: true
          - 
            $ref: "#/parameters/Content-Type"
          - 
            $ref: "#/parameters/If-Match"
          - 
            $ref: "#/parameters/If-Unmodified-Since"
        responses: 
          200: 
            headers: 
              ETag: 
                description: "Entity Tag of the response resource. Used by caches, or in conditional requests (Will be supported in future).\n"
                type: "string"

```

<img width="1261" alt="Screen Shot 2019-08-06 at 7 37 36 AM" src="https://user-images.githubusercontent.com/1591316/62506273-9c753480-b81d-11e9-80d1-1607ad74c221.png">

**Comment by tmkasun** [comment]
Since we do not resolve the swagger definition in UI, we can't dereference the referred parameters. Hence if an API definition contains parameters with references, those parameters will not be shown in API Publisher resources page

What we could do our best is, Show those referenced parameters as read-only parameters but allow to delete them, When deleting the referenced parameter we can remove the reference completely without affecting the component definition
