### ISSUE TITLE
Enable GraphQL API management to perform static query analysis for Rate Limiting

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#5432]

**Comment by HiranyaKavishani** [comment]
https://github.com/ashera96  is looking this

**Comment by ashera96** [comment]
### Static Query Analyser

### **Requirement Analysis**

With GraphQL, the client has the power to ask for exactly what is needed from the backend. This immense flexibility comes at a cost, as the GraphQL API is exposed to severe security implications because the server is no longer in control, the client is. 

If no access control is provided to the GraphQL API, we may end up with a DoS attack due to the execution of malicious queries, which may be intentional or unintentional.

Discussed below is the **Static Query Analyser** which will be used to secure the GraphQL endpoint. The basic idea here is to statically analyze the query within the API Manager, if it turns out to be too complex or too deep when checked against the policy at the gateway level, the request will be blocked and an error message is returned. If all the checks are passed successfully, the request is sent through to the GraphQL backend, which will then return the appropriate response.

![8ea785a4-a4e5-441e-9d38-e0dba4acd2ac-1](https://user-images.githubusercontent.com/30475839/74599824-678c4900-50ae-11ea-81e6-41d8bc71a8bd.jpeg)

### **Suggested Approach**

Static Query Analyser consists of two limitation checks: 
- Query Depth Limitation
- Query Complexity Limitation.

![StaticQueryAnalysis](https://user-images.githubusercontent.com/30475839/74599845-930f3380-50ae-11ea-8a4a-f7380703fc2e.jpeg)

**Query Depth Limitation**

The policy contains:
- Role-depth mappings, while also having a default depth value to fall back to in case no depth value can be assigned for the role of the API invoker.

Through this limitation, we can avoid nested queries which may potentially grow exponentially. When the API is invoked, depending on the role of the invoker the maximum depth allowed within a query is determined through the policy. If the query exceeds this maximum depth, the query will be blocked.

**Query Complexity Limitation**

The policy contains details such as:
- Maximum complexity allowed per query
- Custom complexity values of each and every field under all types found within the schema (default is 1)

When the API is invoked, the complexity of the query is calculated by cumulatively adding each custom complexity value. If this complexity does not exceed the maximum complexity allowed, the request is passed through to the backend. If this threshold is exceeded, the query will be blocked.

### **Implementation**

Once the depth and complexity related policy details are gathered from the API creator, the API is published. If no policy details are added, the default will be to disable both checks.

**Note**: If this particular API was already published, it is a must to re-publish the API in order for the added policy to be applied at API invocation. 

As a precondition, the query is checked against the policy to see if the depth and complexity checks are enabled. If not enabled, those checks will not be performed against the payload. If these checks are enabled, the analysis is performed. 

Firstly, the depth of the payload is checked, if this payload depth exceeds the previously set maximum depth which is allowed depending on the role of the API invoker, the request will be blocked as shown below.

![deep](https://user-images.githubusercontent.com/30475839/74599923-dae28a80-50af-11ea-9050-cedc4849cad4.png)

For example, the above API invocation was done by the admin, and the maximum depth allowed is 3. But, the query which was passed in had a depth of 4. Hence, the query was blocked.

If the depth check is passed and complexity is enabled, the overall complexity of the query is calculated. This calculated complexity is checked against the maximum complexity which is allowed. If it exceeds the previously set threshold value, the request will be blocked as shown below.

![complex](https://user-images.githubusercontent.com/30475839/74599940-fe0d3a00-50af-11ea-9fd1-999d2c498d4e.png)

If both these checks are passed, the request is allowed to pass through to the server.
