### ISSUE TITLE
Delete API confirmation box is not consistent with other message boxes

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#5611]
![image](https://user-images.githubusercontent.com/3960742/65147888-a7d29700-da3c-11e9-9da9-e55dce3df9c3.png)

1. Button has a boundary.
2. Need an image like below?

![image](https://user-images.githubusercontent.com/3960742/65147962-d51f4500-da3c-11e9-978f-ccbe2d2629ed.png)

**Comment by Krishanx92** [comment]
We have **ConfirmDialog** component [1] in both store and publisher to keep the consistence of message boxes. Since delete API confirmation box not use the **ConfirmDialog** component will cause this inconsistency.

[1] https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/ConfirmDialog.jsx

**Comment by chamilaadhi** [comment]
Seems like this is fixed in 3.0.0 beta
<img width="581" alt="Screen Shot 2019-10-12 at 10 46 48 AM" src="https://user-images.githubusercontent.com/4861150/66695303-ad3e9c80-ecdd-11e9-8477-27f8822da0cd.png">
