### ISSUE TITLE
Error/Bug Validators are not working when Creating an API from Swagger file

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5833]
Description:

When creating An API by importing a swagger file the validators used in the create API page is not working unless the value fields are clicked. 

![Screenshot from 2019-09-26 14-26-40](https://user-images.githubusercontent.com/42222921/65674460-38772b80-e06a-11e9-8a74-b4fc60881960.png)

**Comment by chamilaadhi** [comment]
This validation is fixed in 3.0.0 beta
<img width="750" alt="Screen Shot 2019-10-12 at 10 37 05 AM" src="https://user-images.githubusercontent.com/4861150/66700736-b9dce800-ed11-11e9-8d1c-66fb3946000e.png">
<img width="758" alt="Screen Shot 2019-10-12 at 10 38 40 AM" src="https://user-images.githubusercontent.com/4861150/66700737-ba757e80-ed11-11e9-9381-6a9de3b94a25.png">
