### ISSUE TITLE
[Publisher] Cannot change the authorization header at the server level 

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#5856]
**Issue:** 
Neither adding  `<AuthorizationHeader>{authorization-header}</AuthorizationHeader>` 
to the api-manager.xml nor changing the `auth_header`  field in deployment.toml modifies the Authorization Header from its default value.

**Comment by chamilaadhi** [comment]
Working in AM3.0.0 beta. See below

<img width="590" alt="Screen Shot 2019-10-12 at 11 22 28 AM" src="https://user-images.githubusercontent.com/4861150/66695735-ac5c3980-ece2-11e9-9c82-eab8ed51c1c6.png">
<img width="1237" alt="Screen Shot 2019-10-12 at 11 22 39 AM" src="https://user-images.githubusercontent.com/4861150/66695737-afefc080-ece2-11e9-91ad-827f6253dff3.png">


Since https://github.com/wso2/product-apim/issues/6272 is reported by you and it is working now based on your comment, I suppose this is working as well.
