### ISSUE TITLE
No error message after importing swagger definition with errors

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#5880]
After importing a faulty swagger definition it does not update the current definition. However, no error message is displayed.

**Comment by chamilaadhi** [comment]
Fixed in APIM 3.0.0 Beta. Added validation to both upload file and url option

<img width="758" alt="Screen Shot 2019-10-12 at 10 38 40 AM" src="https://user-images.githubusercontent.com/4861150/66695222-8af84f00-ecdc-11e9-998e-6808a1fe78e7.png">
<img width="750" alt="Screen Shot 2019-10-12 at 10 37 05 AM" src="https://user-images.githubusercontent.com/4861150/66695226-8cc21280-ecdc-11e9-93e6-b8a1c4b024d0.png">
