### ISSUE TITLE
issue in devportal -- Testing section key type

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#5982]
In the dev portal TEST section there is a field to select the Key Type. Think we select PRODUCTION as the key type and use a SANDBOX key to invoke the API it executes. In the other way round when we use SANDBOX as the key type and use a PRODUCTION key to invoke the API it executes. This is happening to both JWT and OAUTH2 token types. But for it is not an issue for Oauth2 token as we select the Oauth2 token generated app as the Application and select the key type it fills the Access token field automatically. But for JWT it is not happening likewise.

**Comment by ShanJayaweera** [comment]
This happens when the Gateway environment is Hybrid type. As it handles both production and sandbox token type hope this is not an issue

**Comment by chamilaadhi** [comment]
Can you check whether you have defined a sandbox endpoint for your api? If so, If you invoke using a sandbox token, it will be called using that backend. Otherwise if only the production endpoint is provided,  you will be able to invoke the api using only production key. You won't be able to invoke using a sandbox key.
