### ISSUE TITLE
[Publisher] Issues when a user with publisher role edits certain fields of an API

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#6032]
According to the test case, a user with publisher permission only cannot edit fields in design and implement pages. So a publisher should not be able to edit the thumbnail of a published API.
But the user can edit the thumbnail. 

![image](https://user-images.githubusercontent.com/47671237/65935655-7e037200-e437-11e9-8feb-dd8c0772a9e4.png)
![image](https://user-images.githubusercontent.com/47671237/65935678-92476f00-e437-11e9-8d64-088aac54aad4.png)

Error message when user tries to add new resources:

![image](https://user-images.githubusercontent.com/47671237/65866691-de8ca380-e392-11e9-85ca-5a0799cb0fc9.png)

![image](https://user-images.githubusercontent.com/47671237/65935943-709ab780-e438-11e9-9ea9-a0e8d45bb0e4.png)

Error message when user edits the resource properties(description, summary) and click save icon :

![image](https://user-images.githubusercontent.com/47671237/65866896-37f4d280-e393-11e9-84fe-f69cf6d5c977.png)
![image](https://user-images.githubusercontent.com/47671237/65935894-4943ea80-e438-11e9-988d-19097b43d672.png)

**Comment by chamilaadhi** [comment]
also related to https://github.com/wso2/product-apim/issues/6034

**Comment by TanyaM** [comment]
1. Eventhough we didn't allow publisher to upload a Thumbnail in previous releases it was decided to allow publisher to upload a thumbnail since thumbnail is not a design level detail. Hence the commit [1] will allow necessary permission for publishers.

2. Publishers are not allowed to add new resources hence the new resource adding UI is hidden from publishers.

3. Description and summary fields are marked disabled to publishers since they are not allowed to edit those.

[1] https://github.com/wso2/carbon-apimgt/pull/7357/commits/8c5dbbed611f6148f1984bc4d7d2bbff38c198bd
