### ISSUE TITLE
[Publisher] API Product's Icon change is not reflected in API Products' list view

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6169]
After changing the API Product's icon, change is not reflected in API Products' list view.

![Screenshot from 2019-10-03 11-20-16](https://user-images.githubusercontent.com/54613992/66102408-e38a6680-e5cf-11e9-8f50-7e774d228bed.png)

![Screenshot from 2019-10-03 11-20-47](https://user-images.githubusercontent.com/54613992/66102409-e38a6680-e5cf-11e9-9a10-00e747aec571.png)

**Comment by AmaliMatharaarachchi** [comment]
This can be observed in API list view as well

**Comment by chanaka3d** [comment]
When updating the icon, the top bar icon updating issue is fixed in both product and store.

The listing page thumb is removed ( will do 10 registry call if there are 10 icons ) ... so removed the icons and put the static icon for doc/api/api-product.

https://github.com/wso2/product-apim/issues/6169
