### ISSUE TITLE
No login,logout,signup apis in store.

### ISSUE THREAD

**Issue by nikhil2108** [wso2/product-apim#6223]
version-2.6.0
https://docs.wso2.com/display/AM260/Store+APIs#StoreAPIs-UserSignup
APIs mentioned in above document are deprecated.

Below is new document-
https://docs.wso2.com/display/AM260/apidocs/store/

There are no apis for user signup, login, logout etc. in store apis.
Where can I found those?

**Comment by nikhil2108** [comment]
found it in getting started section. Closing the issue.

**Comment by kavishkafernando** [comment]
Hi Nikhil,

Login is the same as generating an access token. So for the login process you can use the Token API to generate an access token. You can follow document  [[1]](https://docs.wso2.com/display/AM260/apidocs/store/index.html#guide).

[1] - [https://docs.wso2.com/display/AM260/apidocs/store/index.html#guide](https://docs.wso2.com/display/AM260/apidocs/store/index.html#guide)

In order to Logout you can revoke the access token. You can follow document [[2]](https://docs.wso2.com/display/AM260/Token+API#TokenAPI-Revokingaccesstokens).
[2] - [https://docs.wso2.com/display/AM260/Token+API#TokenAPI-Revokingaccesstokens](https://docs.wso2.com/display/AM260/Token+API#TokenAPI-Revokingaccesstokens)
