### ISSUE TITLE
[Publisher] Do not get a timeout error,when the time taken to receive the response from the backend is more than the global timeout value.

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#6305]
![Screenshot from 2019-10-08 12-14-31](https://user-images.githubusercontent.com/31464477/66379107-782b0500-e9d2-11e9-947e-b240fb9cf650.png)
![Screenshot from 2019-10-08 12-14-34](https://user-images.githubusercontent.com/31464477/66379142-82e59a00-e9d2-11e9-8aa1-9650574ea35a.png)
![Screenshot from 2019-10-08 12-16-46](https://user-images.githubusercontent.com/31464477/66379145-84af5d80-e9d2-11e9-914e-f08e58cb6dc5.png)
![Screenshot from 2019-10-08 12-17-11](https://user-images.githubusercontent.com/31464477/66379149-85e08a80-e9d2-11e9-8472-36df8d2d63ca.png)
**Test Case**
An API consumer should receive response - 'Timeout error' when the time taken to receive response from backend is more than the global timeout value configured in synapse.properties
**Issue**
By changing the global timeout value in synapse.properties file & endpoint timeout value in advance configurations and if we passed a query parameter to delay the response from the backend,It gets response from the backend successfully after the given delay time value in query parameter without giving the timeout error.

**Comment by dushansilva** [comment]
Tried this by putting synapse global time out ad 10s, And backed I held the request for 20s, 15s and 12s, Both for 20s and 15s the timeout was successfully shown, however for 12s it was not, 

This can be due to the fact that the we are running a timer task to check the timeout requests and removing the synapse callback. Therefore there is a possibility that the callback is not removed by the timer task exactly at 10s which would be ok, Hence closing the issue
