### ISSUE TITLE
[UX] Text issues and inconsistencies APIM3 - Alpha2

### ISSUE THREAD

**Issue by lakshikap** [wso2/product-apim#6380]
In the API Product 'operation governance' section of the resource, the text is out of the text box. 
Configuration tab - Different fonts used in the caution message.
Scopes tab - Scopes are not being saved although we get a message with success status.
Documents tab - Inconsistent use of words for the same thing like type and category.
Mediation policies tab - The outflow pop-up shows 'Custom IN Mediation Policies' shouldn't this be 'OUT' instead? Same for fault flow.
In the overview part, the screen has small circled question marks which don’t have tool tips.

All screens are here - https://drive.google.com/drive/folders/1EoHPYjGxcEsZ9w1YrlmgLWK7--Xkejgt

**Comment by tmkasun** [comment]
@lakshikap  Can you please make those screenshots public, or attach them directly to github issue

**Comment by tmkasun** [comment]
> Scopes tab - Scopes are not being saved although we get a message with success status.
This is fixed in APIM 3.0 Beta

> Documents tab - Inconsistent use of words for the same thing like type and category.
We have renamed it to `type`and `source`, This is fixed in APIM 3.0 Beta

> Mediation policies tab - The outflow pop-up shows 'Custom IN Mediation Policies' shouldn't this be 'OUT' instead? Same for fault flow.

We have moved the mediation configurations to `Runtime configs` section. This is fixed in APIM 3.0 Beta

> In the overview part, the screen has small circled question marks which don’t have tool tips.

This is also fixed in APIM 3.0 beta

![image](https://user-images.githubusercontent.com/3313885/66744855-22a39c00-ee9b-11e9-835c-e2b5e05511d6.png)
