### ISSUE TITLE
Dev portal top bar needs to be updated to match with the publisher

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6393]
![image](https://user-images.githubusercontent.com/3960742/66640496-b6286300-ec36-11e9-9530-e980ee2fc608.png)

**Comment by bhathiya** [comment]
Need to remove tenant domain from publisher too.

**Comment by tmkasun** [comment]
Removing tenant domain from the user name is fixed now,
![image](https://user-images.githubusercontent.com/3313885/66889625-cce90400-f000-11e9-8cad-0e4be439a16a.png)

regarding the similarity between devportal and publisher, Do we need to make both look alike, currently they have a different position in app name , `Publisher` `Devportal`



![image](https://user-images.githubusercontent.com/3313885/66889658-e7bb7880-f000-11e9-9e09-d3e9c3582c38.png)

![image](https://user-images.githubusercontent.com/3313885/66889662-ec802c80-f000-11e9-8f97-9d80ffb5135b.png)

If we need to make them look alike, I think it's better to share the top navigation bar source code between apps. Otherwise, it would be a copy past of styling from one to another and would be hard to maintain.

@bhathiya WDYT ??

**Comment by bhathiya** [comment]
Yes, they don't need to be the same, but the dev portal RHS section feels too tight. Having some space between text-icon will fix it.

**Comment by bhathiya** [comment]
@AmaliMatharaarachchi please have a look.

**Comment by AmaliMatharaarachchi** [comment]
@bhathiya sure

**Comment by AmaliMatharaarachchi** [comment]
This is fixed in current pack.

**Comment by bhathiya** [comment]
Yes, @kavishkafernando fixed it.
