### ISSUE TITLE
API Invocation URL is not displayed in the Dev Portal

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#6533]
![image](https://user-images.githubusercontent.com/6614042/67148025-4eb68700-f2b8-11e9-9cfa-bfce268e4909.png)

When seeing the overview of an API in the devportal, the API invocation URLs are not displayed(i.e. Production and Sandbox gateway URL + apiContext). This means that an API developer cannot discover the APIs endpoint in order to invoke it from their Application.

**Comment by uvindra** [comment]
Correction, this can be seen by expanding the _more_  section

![image](https://user-images.githubusercontent.com/6614042/67148394-c7b7dd80-f2bc-11e9-90d0-02e4c9cc23d2.png)

So the invocations URLs are displayed

**Comment by rmsamitha** [comment]
**[UX imporovement]** I suggest this "More" section should be a default visible section. Those information is something most basic, isn't it. May be rather than the section 'SDK generation", etc.
And this section doesn't need a whole horizontal row. Half of currently dedicated space is enough. Probably the same space size asAPI Credentials , Resources, etc. is enough.
