### ISSUE TITLE
Unauthorized user redirections doesn't work for api-product pages

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#6537]
API creator user enters below url on browser. 
https://localhost:9443/publisher/api-products
Page keeps loading for ever. Seems Url redirections are not configured for unauthorized users for api-product pages.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2484781/67200981-d6200980-f422-11e9-9577-6bb8eb821615.png">

**Comment by tmkasun** [comment]
BTW, the screenshot you have attached explains you creating a GitHub issue 😄

**Comment by praminda** [comment]
Page keep loading forever and when it looks like it'll never load, app redirects you to create new apim issue. 😄

**Comment by tmkasun** [comment]
Now it's worst, If creator access `https://host/publisher/api-products/` , Page will load without hiding the create API button and , worst part is creators can publish API products as well.

@uvindra FYI 😃

**Comment by uvindra** [comment]
REST API resource scope validation was not taking place due to changes done to support minor version upgrade of REST API without needing to change client code that is using the major version.

This issue has now been fixed. An API creator attempting to navigate to the https://localhost:9443/publisher/api-products page will encounter a 401 when doing a GET on /api-products. But this will still result in the original issue reported by Samitha, where the page loads continuously

![load_fail](https://user-images.githubusercontent.com/6614042/72781740-09537e00-3c48-11ea-95db-84cdc87e086a.png)
