### ISSUE TITLE
Error message should have the API name instead of the UUID

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6589]
![image](https://user-images.githubusercontent.com/3960742/67214972-4d16cb80-f43e-11e9-9582-e24bbc56e576.png)

**Comment by tmkasun** [comment]
Currently, we display the error message that is coming from the error response, But IMO we can't use response error messages directly because they are not i18n translatable. So shall we handle error messages in UI level?

**Comment by bhathiya** [comment]
+1.

**Comment by tmkasun** [comment]
In order to implement that, We need to have some kind of mapping, i:e error code mapping for messages, REST API response should return error code which we map in UI level to messages.

Since we don't have such a mechanism ATM we couldn't differentiate error responses.
i:e

![image](https://user-images.githubusercontent.com/3313885/67261108-c523d680-f4bc-11e9-8633-cf784e1d296d.png)

409 in delete return by different conditions.

in API it's for active subscriptions, in API product it is returned for shared resources.
