### ISSUE TITLE
Secure WebSocket gives a connection reset by peer response

### ISSUE THREAD

**Issue by Arshardh** [wso2/product-apim#6693]

**Comment by dushaniw** [comment]
We need to add <parameter name="wss.ssl.protocols">TLSv1.1,TLSv1.2</parameter> to SecureWebSocketInboundEndpoint.xml.

In addition, in order to call a secured web socket endpoint, having the server's public certificate is sufficient. We need remove the parameter  "wss.ssl.trust.store.file" from the SecureWebSocketInboundEndpoint.xml as well.
