### ISSUE TITLE
[Publisher] [UI] When an API is in published state, wrong requirements for next state transition

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#6728]
When an API is in published state, requirements box display incorrect information.

<img width="1044" alt="requirement-box" src="https://user-images.githubusercontent.com/27903/67825071-c3927980-fa8d-11e9-8c8b-3fac5f5f5a38.png">

**Comment by tmkasun** [comment]
Hi @chintana 

I think the requirement shown here is valid Because if you want to change the state to `Protoyped` (though it's highly unlikely) you need to change the endpoint type to `Prototype endpoint`.

**Comment by chintana** [comment]
Yes, when you have to go to prototyped, that's true. However, for the user it's mentioned as 'Requirements for next state transition'. This imply that after you publish (and you're in the PUBLISHED state) the next stage is prototyped. Which is wrong.

Also I don't think this box belong here. Maybe when we hover over we can show that. Maybe when we're trying to go to back to Promoted, we can popup saying we have to have a prototype endpoint in place or something along those lines

**Comment by tmkasun** [comment]
@chintana 

> This imply that after you publish (and you're in the PUBLISHED state) the next stage is prototyped. Which is wrong.

Agree on this, We will change the message there.

> Maybe when we hover over we can show that. Maybe when we're trying to go to back to Promoted, we can popup saying we have to have a prototype endpoint in place or something along those lines

We initially thought of doing that but later we decided show in the side because

1. User need to `hover` the relevant section in the SVG to show the requirements popup
2. Initially, When the user doesn't know about the `hover` effect, they will have the question , `Why this PUBLISH/PROTOTYPED button is disabled?` We tried to answer that question by showing the unmet requirements.
