### ISSUE TITLE
[Publisher] [UI] Explain what can a user do with properties in the Properties section. What it can be used for etc...

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#6729]
Need to explain what/why we have properties and what use cases / scenarios it can be used for. Otherwise it's not obvious. Yes you can add key value pairs and search, but what else?

**Comment by Tomas-Mrazek** [comment]
FYI we use custom properties for finer control of custom handlers. We have a custom logging handler, which can be disabled by custom property. This is configured in API Velocity Template.

**Comment by tmkasun** [comment]
Hi @chintana-zz ,

I think the usage and sample scenario should be added to the documentation. I don't think explaining the usage of properties in the web application is a good idea. Maybe we could point the users to our documentation page from the web app. 

@Tomas-Mrazek , 

Thank you for the comment, Yes this is exactly one of the most common usage patterns in API properties.

@shaniR , @bhathiya @harsha89 @sanjeewa-malalgoda  WDYT ?

**Comment by wx-yz** [comment]
+1 to point to the documentation. IMO there should be some descriptive text explaining why we need properties "Add custom key/value pairs for providing info to custom handlers. More info here" (not word for word) sort of thing.

Otherwise the UI experience completely decoupled from the documentation and you need to read the doc first to understand what's in the UI. Problems with that approach,

1. Documentation is huge so it takes time to find the right place to look
2. Not intuitive UX - the question I would ask here, is the UI understandable to a completely new user to WSO2 APIM Solution? That user can be user that has experience with other APIM products. So what information/clues we can provide for such a user to make the experience as straightforward as possible

Thoughts?

**Comment by chanaka3d** [comment]
We have added the following helper text on top of the Properties adding screen.

"Usually, APIs have a pre-defined set of properties such as the name, version, context, etc. API Properties allows you to add specific custom properties to the API.

We will be focusing on pointing to the documentation in a more generic way with a future release.
Created the following ticket to track the progress.
https://github.com/wso2/product-apim/issues/7582
