### ISSUE TITLE
No Button to Create API

### ISSUE THREAD

**Issue by saifkamaal** [wso2/product-apim#6773]
HI,

Just installed the latest version 3.0.0 and went ahead to create an API, but unfortunately, the create API button is not visible. 

![Capture](https://user-images.githubusercontent.com/29369768/68293374-411a4300-00a7-11ea-9377-fc581873584e.PNG)

When I tried using publisher, I just can't access the page it keeps giving me 403 error

![Capture1](https://user-images.githubusercontent.com/29369768/68293424-5a22f400-00a7-11ea-8316-ca67a2092f15.PNG)

I have jdk1.8.0_231, installed and I even tried to set the compression to "off" in catalina-server.xml.

Any pointers ?

**Comment by tmkasun** [comment]
Hi @saifkamaal 

> ![](https://user-images.githubusercontent.com/29369768/68293374-411a4300-00a7-11ea-9377-fc581873584e.PNG)

Here, it seems you don't have any published or prototyped APIs in the dev portal. You need to either publish or deploy the API as prototyped to make it available in the **Developer Portal**

> ![](https://user-images.githubusercontent.com/29369768/68293424-5a22f400-00a7-11ea-8316-ca67a2092f15.PNG)

It seems that the user does not have the required permissions to access the `Publisher` application. Can you check the roles assigned to this user? In order to access publisher application, you need to have publisher, creator or admin roles in the user.

Can you attach a screenshot of the localstorage items when you get above 403 error

![image](https://user-images.githubusercontent.com/3313885/68318985-9c6a2680-00e3-11ea-9235-74edc70dc55c.png)

Open browser developer console > goto Application > goto Local Storage

**Comment by saifkamaal** [comment]
bad from my part. Thanks for the info.
