### ISSUE TITLE
Error on Validate of WSDL from Url

### ISSUE THREAD

**Issue by AndreasRusjaev** [wso2/product-apim#6774]
Hello everybody,
in wso2am 3.0.0 i have error on import wsdl from URL.
![ValidateWSDL_Error](https://user-images.githubusercontent.com/18263592/68294336-2f797100-0090-11ea-8a2c-1ca2a16d70f3.png)
The wsdl is correct i can that import with soapUI.
The backend of wso2am i think correct post call on validate-wsdl returned 200 (see network-monitor from mozilla on the inmage).
The error occurred in frontend.
Thanks

**Comment by tmkasun** [comment]
@pahans FYI

**Comment by AndreasRusjaev** [comment]
I think that is not a question, I think that is a bug.
In 2.6.0 this function with my wsl make add correctly.

**Comment by tmkasun** [comment]
@AndreasRusjaev 
To further examine the issue,
Can you share the WSDL URL or file and also share the browser console logs when this issue occurred

**Comment by AndreasRusjaev** [comment]
@tmkasun thanks for comment.
Yes tomorrow I send you the browser console log.
The url I can't share is on my localhost behinds corporate firewall. I can check with other public soap service.
Best Regards

**Comment by AndreasRusjaev** [comment]
Hello everybody,
we have the following wsdl:
<wsdl: definitions targetNamespace = "http://schema.test.de/test">
<Wsdl: types>
<xsd: schema elementFormDefault = "qualified" targetNamespace = "http://schema.test.de/test">
<Xsd: annotation>
<xsd: documentation> 2.0.8 (2017-06-13 13:06:35) </ xsd: documentation>
</ Xsd: annotation>
<xsd: import namespace = "http://schema.test.de/artefakte/test" schemaLocation = "test.xsd" />
...
</ Wsdl: types>
</ Wsdl: definitions>
Important is schema location of test.xsd which is relative to wsdl on our serever.
All other tools are relative to server url.
wso2am-3.0.0 search in the directory where it is installed. see ValidateWSDL_Error.txt
[ValidateWSDL_Error.txt](https://github.com/wso2/product-apim/files/3818419/ValidateWSDL_Error.txt)

**Comment by Tomas-Mrazek** [comment]
I have the same problem. APIM searches import file in it's file system instead of relative path to server via `?xsd=<file.xsd>`

WSDL cannot be properly parsed, when published by Enterprise Integrator 6.4.0 and xsd import is present.

Enterprise Integrator with proxy WSDL url `http://<EI>/services/SomeProxy?wsdl`
Specified import: `<xs:import namespace="http://wso2.someurl.com/types/xsd" schemaLocation="SomeProxy?xsd=SomeXsdSchema"/>`

Calling url `http://<EI>/services/SomeProxy?xsd=SomeXsdSchema` works as expected.

This issue is directly related to https://github.com/wso2/product-apim/issues/6415 reported by me month ago.

**Comment by malinthaprasan** [comment]
Hello @AndreasRusjaev @Tomas-Mrazek 

We have fixed this in https://github.com/wso2/carbon-apimgt/commit/d595436c0c7b991950601bb477ae840f7bfccbb1
