### ISSUE TITLE
When API is updated the msg is displayed twice

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#6857]
Issues raised by Usability Testing candidates

**Comment by chathuranga95** [comment]
Two Info messages are shown at the same time for the following scenarios on the publisher. 
* When lifecycle state is changed
* When subscription configurations updated
* When a scope is added/deleted

Following info messages are displayed simultaniously.
* ${api_id} updated successfully / error
* ${scenario} updated successfully / error

If the above is the expected behaviour, please close the issue, Otherwise, only either specific update scenario message or ${api_id} updated status message can be displayed.
