### ISSUE TITLE
Prototype APIs can't be used for API products

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6912]
$subject. 

The inline script is not copied to the API product synapse. Hense invocation fails.

**Comment by uvindra** [comment]
Since API Products will be created by API Publishers at a business level, providing the ability to include Prototype APIs does not seem a valid use case.

Prototype APIs should only be used at the initial stages of API development. Hence we have decided to exclude Prototype APIs from being used to create API Products.

**Comment by uvindra** [comment]
We do not have a generic method of restricting Prototype APIs from being returned when doing an apiGet on the publisher REST API. Hence we will be filtering these out at the UI level before displaying them in the API Product resource selection window.

**Comment by bhathiya** [comment]
I hope we can/should do the validation at the back end too.

**Comment by chanaka3d** [comment]
Filtered APIs at the UI level. Fixed with PR https://github.com/wso2/carbon-apimgt/pull/8086

**Comment by bhathiya** [comment]
what about the backend validation?

**Comment by uvindra** [comment]
@bhathiya , see my previous comment

> We do not have a generic method of restricting Prototype APIs from being returned when doing an apiGet on the publisher REST API. Hence we will be filtering these out at the UI level before displaying them in the API Product resource selection window.

In order to support this at the backend we will need to add new functionality to allow the caller to specify the life cycle they are interested in as a filter or we need a new REST API resource that excludes Prototype APIs. Both these options are too specific to warrant changing the REST API, hence we choose to do this at UI level since this is a specific API Product UI requirement.

**Comment by bhathiya** [comment]
I was referring to the validation in api product add path. If the given set of API has a prototype API included, we can disallow the request.

**Comment by uvindra** [comment]
Yes I think validating at this level should be possible.

For completeness, shall we block the following life cycle states explicitly?

PROTOTYPED
BLOCKED
DEPRECATED
RETIRED

So attempting to create an API Product, with an API which has one of the above life cycle states will fail.

**Comment by bhathiya** [comment]
+1, except for the BLOCKED state. BLOCKED is mostly a temporary state. Therefore, I think we should allow it.

**Comment by uvindra** [comment]
Regarding BLOCKED, there are two things that need to be taken into consideration here.

1. BLOCKED is meant to be a temporary state that the Publisher would revert to to prevent a given API from being invoked. When the state will change will be at the complete discretion of the Publisher.

2. If we allow an API Product to be created using the resources of a BLOCKED API, we will essentially be allowing access to the above BLOCKED APIs resources via the API Product(This is because the API Product & its resources are deployed as an independent artifact on the API Gateway ). So at this given time the API Product has subverted the intention of the Publisher who BLOCKED the API initially.

Due to above conflict of intentions, it has been decided to prevent creating API Products using API BLOCKED APIs.
