### ISSUE TITLE
Change application token type names in developer portal

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-apim#7027]
Current Token types are JWT and OAUTH. This gives wrong perception since JWT is a token format and OAUTH is a protocol/specification. So proposing to change the token type names in the developer portal as below.

Reference (Opaque)
Self-contained (JWT)

<img width="538" alt="Screen Shot 2019-11-29 at 09 36 49" src="https://user-images.githubusercontent.com/8766778/69859367-ed58df00-128b-11ea-8597-ddf3b38076fc.png">

**Comment by tmkasun** [comment]
Hi @godwinamila ,

Thanks for your suggestion, In here we have shown the commonly used names rather than being technically correct. I think these two words (OAuth & JWT) could be easily understood by a person who is not coming from the IAM domain as well.

So in your suggestions

- **Reference (Opaque)** Will users get this as OAuth
- **Self-contained (JWT)** +1

@bhathiya , @sanjeewa-malalgoda , @harsha89 & @nuwand  WDYT?

**Comment by fazlan-nazeem** [comment]
@tmkasun  yes, this was agreed on the mail discussion to use the names as above. Shall we proceed with this so the docs can be aligned with the modified names as well?
