### ISSUE TITLE
[AM-3.0.0] API security level cannot update after only selecting Mutual SSL Mandatory security scheme.

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-apim#7284]
When Mutual SSL mandatory option is selected without any transport-level scheme for an API, a user can't enable/disable application-level/transport-level security scheme by editing the API.

**Steps to Reproduce**

1. Create an API by enabling **only** Mutual SSL mandatory security scheme from the publisher.
2. Save API.
3. Again edit the API and try to add application-level security and save. There is an error stating subscription tiers are not available.

**Comment by tmkasun** [comment]
Hi @Dumindu-Kanchana 
Thanks for reporting this issue, We were able to reproduce this issue and accept that this is a valid scenario. We will fix this in the next release.

Thanks

**Comment by tmkasun** [comment]
In an offline chat had with @sanjeewa-malalgoda , We discussed to remove the validation happens when updating the Bussiness plans (subscription tiers) in the Publisher portal. 
So API developers (in Publisher portal) will able to choose business plans for their APIs even the Oauth2 security schema is not enabled for that API 

@tharindu1st , @malinthaprasan can you please give your opinion on this ?

**Comment by vithu30** [comment]
Similar issue is tracked in https://github.com/wso2/product-apim/issues/7486. Closing as duplicated.
