### ISSUE TITLE
[APIM-3.1.0] Migration documentation from 3.0.0 to 3.1.0 (currently in alpha)

### ISSUE THREAD

**Issue by jkirch57** [wso2/product-apim#7301]
### Description:
Hello,
I would like to know if there is a documentation that explain how to migrate from APIM 3.0.0 to 3.1.0 ? If yes could you give me the link to this migration workflow and if not is it planned to have this documentation for the 3.1.0 final release ?

Today we have a distributed deployement of the 3.0.0 version but we can't use it with secured API because of this issue #7156 with oracle DB. That's why I would like to migrate my current 3.0.0 version to the 3.1.0 alpha version but didn't found any documentation.

Regards,
Jérôme.

**Comment by Krishanx92** [comment]
@jkirch57 
We do not recommend to migrate to the 3.1.0 Alpha since it is already in the development stage.
Issue https://github.com/wso2/product-apim/issues/7156 will solve with following fix https://github.com/wso2/carbon-apimgt/commit/bea7bea6f2b8b47b6751ec858061a2657f1b0590.

One option is to manually build the carbon-apimgt https://github.com/wso2/carbon-apimgt/releases/tag/v6.5.439 tag with the mentioned fix and add as patch version to the APIM-3.0.0.

Or else you have to wait until APIM-3.1.0 release. We have tracking Migration changes here https://github.com/wso2/product-apim/issues/7347 and Docs are not finalizing yet.

**Comment by HiranyaKavishani** [comment]
Closing the issue as per above comment. if need, feel free to re-open it
