### ISSUE TITLE
[Devportal] Can't load devportal home page

### ISSUE THREAD

**Issue by teodora-mitrovic** [wso2/product-apim#7427]
### Description:

After the start of the API manager server script (wso2server.sh), Dev portal home screen is not showing, the loader sign is in loop.

It throws  **Uncaught SyntaxError: Unexpected token (**  in index.bundle.js (the file is uglified and probably minified, so the line of the code where the error is, doesn't give much information)

All requests return code 200, except get settings.js returns 304 (not modified).

### Affected Product Version:
wso2am 3.0.0

### Environment details (with versions):
- OS: Oracle Linux Server 6.8 ( I saw that the apim is not tested on this version, but the other two 
 portals - publish and mgt work fine)
- Client: Chrome 52.0.2743.82 (64-bit)
- Env (Docker/K8s): VM

---

**Comment by CrowleyRajapakse** [comment]
Hi @teodora-mitrovic ,
Can you provide the content in chrome developer tab console and also any errors printed in the <APIM_HOME>/repository/logs/wso2carbon.log. Also try out accessing devportal with cache and cookies cleared.

**Comment by tmkasun** [comment]
Hi @teodora-mitrovic ,

We do not support the Chrome version 52.0.2743.82 that you have used, Chrome 52 is about three and a half years old now (which was released on 2016-08-3)

Following are the minimum browser versions that supports to run APIM 3.0 web portals

```json
 chrome: '58',
 edge: '16',
 firefox: '56',
 safari: '11',
```

[Source](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/babel.config.js#L39-L42)

**Comment by teodora-mitrovic** [comment]
Hi ,

@CrowleyRajapakse 
Error from chrome developer console tab is mentioned above in issue description (Uncaught SyntaxError: Unexpected token ( ).  
Regarding the log file, there are no errors, just information about starting the 3 portals.
I tried deleting cache, same error appears.

@tmkasun
Like I said I saw system requirements, but I am limited to the version of OS and Chrome installed on Virtual Machine. 
Also, publisher portal and mgt console work just fine as I mentioned, so I don't know why would dev portal have problem with Chrome version then.

Thank you both, anyway :)

**Comment by tmkasun** [comment]
Hi @teodora-mitrovic 

This is most probably due to having unsupported JS syntax in the bundle, 

> Also, publisher portal and mgt console work just fine as I mentioned, so I don't know why would dev portal have problem with Chrome version then.

The reason is , we don't maintain the minimum browser compatibility manually, We have used  Babel [browser integration](https://babeljs.io/docs/en/babel-preset-env#browserslist-integration) plugin to specify the browser compatibilities.

So when building the application, Bable converts (transpile) the JavaScript(JS) source into the specified minimum browser compatible syntax, But not beyond that. So if we have used some JS semantic, which can get transpiles into unsupported semantic in Chrome 52.

You could lower the chrome version in the `babel.config.js` file try to access the developer portal.

**Comment by teodora-mitrovic** [comment]
Hey @tmkasun,

I have managed to load Dev portal via Mozilla Firefox in the end.
Thank you for all your help :)
