### ISSUE TITLE
Custom grant configuration gets deleted from identity.xml

### ISSUE THREAD

**Issue by ankit-agrawal07** [wso2/product-apim#7473]
### Description:
I am running a standalone binary of WSO2 APIM v3.0.0 on my machine. For POC purpose, I tried using the mobile grant by following the documentation https://apim.docs.wso2.com/en/3.0.0/Learn/Extensions/writing-custom-grant-types/

Every time the server restarts, it deletes the configuration added in <PRODUCT_HOME>/repository/conf/identity/identity.xml file to register the new grant type.

### Steps to reproduce:
1. Download the custom-grant build jar from https://is.docs.wso2.com/en/5.9.0/learn/writing-a-custom-oauth-2.0-grant-type/
2. Put the jar in <APIM_HOME>/repository/components/lib directory.
3. Add the mobile grant to supported grant type in <PRODUCT_HOME>/repository/conf/identity/identity.xml file (as mentioned in docs)
4. Start the server. The configuration that we made in identity.xml will be lost.

### Affected Product Version:

3.0.0

### Environment details (with versions):
- OS: Windows 10
- Client: 
- Env (Docker/K8s): Standalone product (binary)

---

**Comment by CrowleyRajapakse** [comment]
Hi @ankit-agrawal07 ,
When adding the custom grant handler you need to define that handler in the deployment.toml file instead of trying to change the identity.xml. You can add the following sample configuration to the <APIM_HOME>/repository/conf/deployment.toml file.
```
[[oauth.custom_grant_type]]
name="mobile"
grant_handler="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrant"
grant_validator="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrantValidator"
[oauth.custom_grant_type.properties]
IdTokenAllowed=true 
```
With the new configuration model, if you need to add or change any config you need to do that using the deployment.toml. Otherwise, when the server restarts the templated default configs will be applied.
