### ISSUE TITLE
[AM-3.0] - Unable to install WSO2 as a windows service with YAJSW 11.03 and 12.13a

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#7512]
### Description:
I tried to install WSO2 APIM 3.0 as a Windows Service but was unable to install it successfully. 

### Steps to reproduce:

1. Downloaded and executed WSO2 APIM-3.0 from here[1].
2. Downloaded and extracted YAJSW 12.13a.
3. Changed the wrapper.conf file located in <YAJSW_Home>/conf directory. 
4. Then I executed the below command in <YAJSW_Home>/bat directory.
           _runConsole.bat_
But the service was not installed successfully.

I tried the same with YAJSW 11.03 but observed the same.

[1] https://wso2.com/api-management/#
### Affected Product Version:
APIM 3.0.0

### Environment details (with versions):
- OS: Windows 

---

**Comment by RakhithaRR** [comment]
There's a compatibility issue with the YAJSW version and the Java version installed.
For YAJSW 11.03, use Java 8
for YAJSW 12.14, use Java 11

Also, there seems to be an issue with the minimal wrapper.conf configuration provided in the documentation. Use the configuration provided at the `<PRODUCT_HOME>/bin/yajsw/` in `<YAJSW_HOME>/conf/` instead of the one in the documentation.

**Comment by Krishanx92** [comment]
https://github.com/wso2/product-apim/issues/7435
