### ISSUE TITLE
[Publisher] Can't publish API with only mutual SSL security

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#7522]
### Description:

From the API publisher lifecycle page, Can't publish an API which has only Mutual SSL security configurations

![image](https://user-images.githubusercontent.com/3313885/74937248-b240f480-5411-11ea-8b62-1c45450157c5.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
Hi @isuruh15,

I think this PR https://github.com/wso2/carbon-apimgt/pull/8233 only change the `PUBLISH` button disable condition, We have to update the checklist items shown in the lifecycle page as well.

![image](https://user-images.githubusercontent.com/3313885/75130839-523e9c80-56f6-11ea-8878-df62509ac695.png)

We need to check
- Is mutual SSL enabled
    -  If so check whether at least one certificate is associated with mutual SSL

**Comment by kavishkafernando** [comment]
@isuruh15

If Mutual SSL is enabled we need to add another checklist item as following under Publish
 
**Publish**
- Certificate provided

We need to check whether this condition is satisfied. If this condition is satisfied only the Publish button should be enabled.

**Comment by isuruh15** [comment]
@kavishkafernando 
As we are getting a business plan as a mandatory requirement when we are adding a new cert, do we need to explicitly say that a business plan has provided? 
what if we conditionally show either Business plan(s) provided or Certificate provided depending on the transport layer security preference?

**Comment by kavishkafernando** [comment]
By conditionally rendering business plans and certificate provided, users will get the impression that business plans are not a mandatory requirement. 
Since business plans are certificates are both mandatory I think they should both be displayed in the requirements list.
Business plans and endpoints are a mandatory requirement of any API (except for prototyped) so I think we should maintain that uniformity.
