### ISSUE TITLE
Migrate custom roles on update from 2.6 to 3.0

### ISSUE THREAD

**Issue by grego9** [wso2/product-apim#7628]
Hi, I've successfully updated apim from 2.6 to 3.0. Everything works fine, except user roles. I have several custom roles that doesn't seem to be working from one version to another.
I've been reading and playing around with tenant-conf.json, but can't really figure out how to do this right.

I am able to login only with admin on publisher. And a I can see all my users and custom roles on carbon console, but any of the permission are effective. No errors on log files.

There is something I should check?

Thank you

**Comment by menakaj** [comment]
In APIM 3.x the UI uses the API Publisher and Store REST apis, which are protected with access token and scopes. These scopes are by default mapped to Internal roles. Internal/publisher, Internal/creator and Internal/subscriber.

You can check this in the tenant-conf.json file.

```
"Scope": [
      {
        "Name": "apim:api_publish",
        "Roles": "admin,Internal/publisher"
      },
      {
        "Name": "apim:api_create",
        "Roles": "admin,Internal/creator"
      },.
      .
      .
```

When using custom roles, you have to add that specific role to the proper scope's roles list in order to grant the specific resource access.

Ex: If the custom role org_publisher is used to grant publisher permission, that role should be added to all the scopes which contain Internal/publisher role in the tenant-conf.json. 

```
"Scope": [
      {
        "Name": "apim:api_publish",
        "Roles": "admin,Internal/publisher,org_publisher"
      },
      {
        "Name": "apim:api_create",
        "Roles": "admin,Internal/creator"
      },
      {
        "Name": "apim:api_view",
        "Roles": "admin,Internal/publisher,Internal/creator,Internal/analytics,org_publisher"
      },
      {
        "Name": "apim:api_delete",
        "Roles": "admin,Internal/creator"
      },
      {
        "Name": "apim:subscribe",
        "Roles": "admin,Internal/subscriber"
      },
      {
        "Name": "apim:tier_view",
        "Roles": "admin,Internal/publisher,Internal/creator,org_publisher"
      },
```

The other option is, assigning the proper Internal/* roles to each of the users. 
But, this can be a difficult task if you have several users in your system. 

Therefore the best option is to add the custom role in the tenant-conf.json file.

**Comment by menakaj** [comment]
In the 3.1.0 release, we will provide a UI in the admin portal to configure the scopes and roles.

**Comment by grego9** [comment]
Now I get it. Thank you both for your answers
