### ISSUE TITLE
GatewayResourceCacheExpiry time or DefaultCacheTimeout is not working for resource cache as expected.

### ISSUE THREAD

**Issue by NikithaUdeshana** [wso2/product-apim#7700]
### Description:
We can configure the Gateway cache expiry time with the GatewayResourceCacheExpiry parameter in the api-manager.xml file. If this parameter is not set, then the DefaultCacheTimeout value has to be applied as the cache timeout period. However, it seems both of these parameters are not working properly with the resource cache.

This issue can be observed while evaluating CacheProvider.getResourceCache() method in the APIAuthenticationService class. The resource cache persists even after with the GatewayResourceCacheExpiry time and DefaultCacheTimeout period.

### Affected Product Version:
APIM 2.6.0

**Comment by Shehanir** [comment]
When we conduct tests with running product we couldn't observe this behaviour and the resource cache expired after the timeout period as expected. When we test holding the debugger, we can observe that at some debug points the resource cache didn't cleared. but after debugging further it's getting cleared and updated.  Since this is not reproduced in the running product, we are not currently addressing the issue with a fix.  If this issue occurred at the running product we'll look into this again.
