### ISSUE TITLE
api image missing from store

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/product-apim#7827]
### Description:

I am performing export-import api operation on the same apim server, which results in success. Even I am able to publish it but when I visit the store, the icon of published api is missing.

### Steps to reproduce:

export api

change api name, context and context template in api.json

import api

publish api

go to store

imported api should contain thumbnail api

### Affected Product Version:

wso2-apim-2.2.0

### Environment details (with versions):
- OS: linux
- Client:
- Env (Docker/K8s):

---

**Comment by prasa7** [comment]
Hi ,

Can you log into the management console and check wether the image resource exists in it

You can find the image resource path by store image link as follows

<img width="1335" alt="Screenshot 2020-03-26 at 12 15 49" src="https://user-images.githubusercontent.com/805274/77618086-a8a03480-6f5b-11ea-8176-a80e915e1169.png">

AS en example If the image path is as below
`https://192.168.8.100:9443/registry/resource/_system/governance/apimgt/applicationdata/icons/admin/PizzaShackNII/1.0.0/icon`

Omit the following part https://192.168.8.100:9443/registry/resource and get the registry resource path as below

`/_system/governance/apimgt/applicationdata/icons/admin/PizzaShackNII/1.0.0/icon`

Then go to the registry browser and check whether the image exists there as below and get back to us. (You can click the download button and check)
<img width="1218" alt="Screenshot 2020-03-26 at 12 20 21" src="https://user-images.githubusercontent.com/805274/77618538-83f88c80-6f5c-11ea-83c9-84af4f9145e7.png">

You can log in to the management console with https://localhost:9443/carbon url along with admin user credentials.

Hoping to here the feedback from you since its working in my end.
Thanks
@prasa7
