### ISSUE TITLE
Introduce simple in-built approval/rejection workflows

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#8251]
### Describe your problem(s)
When someone wants to have a human intervention for approval or rejection process for tasks such as application creation, subscription, etc, they have to enable WS workflows and plug BPS engine (WSO2 EI). 

For complex scenarios, having a BPS engine is useful. But for a simple approval/rejection task, this adds some additional overhead (needs an additional server, etc). So having an inbuilt workflow to do simple approval/rejection would be beneficial for a simple scenario

**Comment by chamilaadhi** [comment]
Sub task https://github.com/wso2/product-apim/issues/8253

**Comment by SahanHerath** [comment]
**Describe our solution**
 We have added the Approve Workflow Executor to the system as a solution to this problem. We can use the Approval Workflow Executor for a simple approval/rejection process. 
The flow of the Approval Workflow Executor is looked like this.
![Untitled drawing(4)](https://user-images.githubusercontent.com/45681406/85121406-5614a280-b242-11ea-8f55-f9f8919218cc.jpg)
We have added the Approval Workflow Executor for application creation, application registration, API state change, subscription creation, and user self sign up. Rather than sending data to the BPS, we have kept data in the database and we have added extra columns WF_METADATA and WF_PROPERTIES. WF_METADATA to maintain internal details and WF_PROPERTIES is to maintain external details.
And we have added two rest APIs.
/workflows - getting workflow pending requests according to workflow type
/workflows/{externalWorkflowRef} - getting a workflow pending request from the external workflow reference.

**Working Scenario**
1. When you implement the workflow pending process like application creation, subscription creation, etc. From that process, it calls the execute() method. from there we have store the details of workflow pending request into the database.
2. It uses the rest APIs to get the workflow pending requests from the database and show them in admin dashboard.
3. Workflow Pending requests are approved or rejected through the admin dashboard. It uses the existing rest API,  /update_workflow_status. Through that rest API, it calls the complete() method and completes the update workflow status process.

**Comment by SahanHerath** [comment]
**Admin Dashboard UI for Approve/Reject Workflow Pending Requests.**
When there is no workflow pending requests we show small description of each type of workflow pending request. Through Help, you can know how to enable Approval Workflow Executor for each type of process.
![Screenshot from 2020-06-19 17-40-45](https://user-images.githubusercontent.com/45681406/85132634-cd543180-b256-11ea-8b0e-992d3202acdb.png)
 You can approve or reject the selected workflow pending request by just clicking in Approve or Reject button. Elapsed time for each of the workflow pending requests is shown in there and also created time is shown as a tooltip.
![Screenshot from 2020-06-19 17-40-27](https://user-images.githubusercontent.com/45681406/85133488-68014000-b258-11ea-84b9-f06fd65a5356.png)

**Comment by SahanHerath** [comment]
**Tests for Approval Workflow Executor**

I have added tests to check the process of Approval Workflow Executor.
1. testAPIWorkflowProcess
2. testApplicationWorkflowProcess
3. testSubscriptionWorkflowProcess
4. testRegistrationWorkflowProcess
5. testUserSignUpWorkflowProcess
6. testCleanUpWorkflowProcess
7. testPendingTaskWorkflowProcess

The flow of the test can be understood from this.
[](https://docs.google.com/spreadsheets/d/1HyPknR8RM7kRN3nvRAefR17NzFP-Aj7ZBHQVnws_U0A/edit#gid=0)

**Comment by chamilaadhi** [comment]
Backend https://github.com/wso2/carbon-apimgt/pull/8660

**Comment by chamilaadhi** [comment]
UI https://github.com/wso2/carbon-apimgt/pull/8703

**Comment by chamilaadhi** [comment]
Integration Tests https://github.com/wso2/product-apim/pull/8395

**Comment by SahanHerath** [comment]
#https://github.com/wso2/carbon-apimgt/pull/8660 
#https://github.com/wso2/carbon-apimgt/pull/8703
#https://github.com/wso2/product-apim/pull/8395
##https://github.com/wso2/carbon-apimgt/pull/8756

**Comment by SahanHerath** [comment]
Additional Changes in backend and UI
#https://github.com/wso2/carbon-apimgt/pull/8756

**Comment by chamilaadhi** [comment]
Docs https://github.com/wso2/docs-apim/pull/1439
