### ISSUE TITLE
Publisher Scope Creation - Unnecessary network calls on scope name typing

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#8455]
### Description:
When creating a new scope with the publisher UI, the scope name text box change event sends a network call.

### Steps to reproduce:
1. Login to publisher.
2. Click `Scopes` tab.
3. Click `Add new Scope`
4. Type a scope name

On the developer tools --> Network tab, the network calls per scope name's character are listed.

![scope-network-calls](https://user-images.githubusercontent.com/25490163/85654349-cd778580-b6cb-11ea-9063-87df655c84ca.png)

### Affected Product Version:
API Manager 3.2.0

### Environment details (with versions):
- OS: Ubuntu 20.04

#### Suggested Labels:
React-UI

**Comment by tmkasun** [comment]
This is the expected behavior, We make scope validation REST API call with every `onChange` even on the scope name input, That means for every character you type we send the scope name value that you have entered so far to the backend to get it validated. `404` means there is no such scope with the name provided.

So this is not an issue I guess @chathuranga95  ?
