### ISSUE TITLE
Changing Subscription Throttling Policies takes effect only after restarting APIM

### ISSUE THREAD

**Issue by choesterle** [wso2/product-apim#8514]
### Description:
I have 2 subscription policies defined:
- demo (requestCount 5/month)
- bronze (requestCount 1000/month)
When a user subscribes with the "demo subscription policy" and hits 6 requests, APIM returns error code 900804 (Message throttled out). So far so good. 

When the user now unsubscribe and subscribe again with the "bronze subscription policy" and hits another request, APIM still return error code 900804 (Message throttled out), even if token is revoked and recreated.

Restart of the APIM fixes the problem, but in productive environment not a suitable workaround

### Affected Product Version:
WSO2 API-M v3.0.0

### Environment details (with versions):
- OS:
Ubuntu 20.04 LTS
---
#### Related Issues:
maybe https://github.com/wso2/product-apim/issues/7507

**Comment by ruks** [comment]
@choesterle this is expected if you used the same token to access API even after the re-subscription. If the token is different there will be a cache miss and try to validate the token again at the KM side. Once the subscriptions are validated new subscriptions details will be returned to GW. 
So the throttling divisions are evaluated based on this new subscription-related data. 

What's the token type you used? Can you confirm again you face this issue even with different tokens? Also, make sure application-level and resource level throttling is set to unlimited to verify this. Otherwise, it may be throttled but due to different reasons.

**Comment by choesterle** [comment]
Hi @ruks 

after changing the subscription, I revoke the token by calling HTTP-POST https://192.168.154.128:8243/revoke and recreate a new token HTTP-POST https://192.168.154.128:8243/token. I can also see, that after recreating the token, a different access_token is returned.
The tokenType I use is "JWT" and yes, it seems that I face this issue also with different tokens. And I only define throttling on subscription level (not application-level nor resource level)

BR,
Christian

**Comment by choesterle** [comment]
Anyhow, I'd like to shortly describe my requirements because maybe there is another/better solution to achieve this:
We'd like to offer REST API's with WSO2. To enable prospective consumers to test our API's, we'd like to give them a limited access with 50 Requests/API. If they finally get customers (and pay for the API's) they will get unlimited access.

**Comment by tharindu1st** [comment]
@choesterle  in 3.2.0 onwards this was addressed from handling from Inmemory Subscription validation. 
And from 3.2.0 onwards you'll not need to unsubscribe from API so you can update the throttle policy from subscriptions view.
