### ISSUE TITLE
Remove support for Opaque token generation

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#8622]
### Describe your problem(s)
Remove support for Opaque oauth token generation and only allow JWT oauth token generation out of the box. This decouples the gateway completely from the key manager allowing for more freedom for innovation.  

### Describe your solution
This needs to be restricted from both UI level and REST API level

**Comment by stefanonegri** [comment]
hi, has been this included in 3.2.0? I see I can't create opaque token based applications however the documentation still report this chance; Moreover, what if a customer requires the opaque tokens?

**Comment by nadeesha5814** [comment]
Having the option to generate an Opaque token is still a valid requirement, is there a way to make this configurable or revert back to the previous behaviour.

**Comment by lpastor74** [comment]
Is there any resolution or comment on this? Customers are confused.

#### Suggested Labels:

revert request

**Comment by knightbeat** [comment]
Even if it is true that any sensitive data can be removed from the JWT, some organisational security policies don't allow room for such events at an architectural level. Therefore, the security architects who are accountable for verifying (or giving the green light for) the architecture will refuse to allow JWT/Self-contained token instead of a reference token. From their point-of-view, it is leaving room for potential security issues from an organisational policies point of view.

**Comment by nuwand** [comment]
Reference tokens have become obsolete. All major IDPs have stopped or in the process of retiring the support for reference tokens. Reference tokens only work on systems where the resource server has access (is co-located) to the authorization server. As more and more systems become distributed and hybrid in nature the use of reference tokens will eventually cease. Organizations have full control of what information they include in the JWT. So the belief that self-contained tokens will reveal confidential information is false. If this was true, OIDC would be a complete failure because the OIDC protocol does the same thing of giving a client an ID token that contains non-confidential identity information. I don't think its a good idea to make significant design decisions on product features due to incorrect beliefs.

**Comment by isharac** [comment]
This has been implemented since the APIM 3.2.0.
For backward compatibility, APIM 3.2.0 still support Reference tokens for old Reference token type applications.

**Comment by stefanonegri** [comment]
Hi regarding the security of JWT token, how the revocation will work; is it still possible with JWT tokens?

**Comment by nuwand** [comment]
Yes, there is no change to the token revocation functionality. Users have to revoke token just like revoking any opaque token.
