### ISSUE TITLE
[3.2.0] Get Test Key is not generating Access tokens with global scopes

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9087]
### Description:

The `Get Test Key` in Devportal is not generating Access tokens with the mapped Global scopes. But, when we have local scopes defined and mapped with the API resources, the `Get Test Key` generates an access token with all the mapped local scopes.

### Steps to reproduce:

- Start the API Manager
- Go to Publisher Portal and publish an API
- Go to Scopes view on the Top navigation bar and create a scope (please note that the local scopes are working)
- Engage the scope with any of the API resources
- Go to the Devportal -> Subscribe to an Application
- Go to `Try-out` section and click on `Get Test Key` and examine the JWT Access token

### Affected Product Version:

- API Manager 3.2.0 - RC5

**Comment by athiththan11** [comment]
Please find the screenshot of the Request Payload captured from the Network tab

<img width="636" alt="Screenshot 2020-08-16 at 22 33 41" src="https://user-images.githubusercontent.com/29927177/90339794-da9c5b00-e010-11ea-8fe3-a7cf5f866242.png">

**Comment by kavishkafernando** [comment]
Hi @athiththan11 
Get TEST KEY only generates a default access token. It doesn't generate a token with specific scopes. 
If you want to generate a token with specific scopes you need to go to the application view and do it.
Since it is a "Test" key only default scopes are used for the generation of the token.

**Comment by athiththan11** [comment]
Hi @kavishkafernando 

Thank you for getting back on this with your insights.
I was able to generate the test tokens with the scopes using the Get Test Key from the Devportal. Please find the attached screenshots, where I have created a local scope and attached to one of the API resources, and the `Get Test Key` request payload captured from the Network console

- Publisher: The List of local scopes

<img width="1240" alt="Screenshot 2020-08-18 at 10 26 39" src="https://user-images.githubusercontent.com/29927177/90472105-5c89a280-e13d-11ea-979b-6385be449d97.png">

- Publisher: Engaging a local scope with the API resource

<img width="1392" alt="Screenshot 2020-08-18 at 10 18 09" src="https://user-images.githubusercontent.com/29927177/90471911-f4d35780-e13c-11ea-838a-1f995b059c04.png">

- Get Test Key: Generation of token gets me with all the engaged scopes

<img width="650" alt="Screenshot 2020-08-18 at 10 21 06" src="https://user-images.githubusercontent.com/29927177/90471946-04eb3700-e13d-11ea-902b-066c4e1ad23f.png">

Could you please verify this behavior locally and revert back?
Thanks in Advance!

**Comment by kavishkafernando** [comment]
Hi @athiththan11 

Yes it will use **all the default local scopes** attached to the api when generating test key as i mentioned before. If a token is needed for a **specific** scope the user will have to go to the application view and generate access token.

As for the issue you have mentioned in [1] it has been fixed with commit [2]

[1] - https://github.com/wso2/product-apim/issues/9087#issuecomment-674551659

[2] - https://github.com/chanaka3d/carbon-apimgt/commit/527aa6d220f659dde5fa48748d004191a10acc86

**Comment by athiththan11** [comment]
Hi @kavishkafernando 

Yes, you are correct, and thank you for the fixes.
This issue was opened to mention that none of the engaged Global (a.k.a Shared) scopes were there when performing the Get Test Key function (as you and I have explained and observed earlier, all the engaged local scopes are retrieved but not the shared scopes).

Hope you understand the background of this issue now, and apologies if I have miscommunicated any terms in my previous responses. Furthermore, yes I agree that if I want to generate an Access token with only a specific scope, I have to use the Application view to generate the tokens.
