### ISSUE TITLE
Improve Debug Logs in Web Socket API

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-apim#9213]
#### Suggested Labels:
wso2am-2.6.0

**Comment by deelaka96** [comment]
Hi All,

The requirement is to have more detailed debug logs in the WebSocket API flow in order to be more helpful to debug in an erroneous scenario. 
Currently, We have added the following logs to print the inbound outbound URL in the flow.
Please refer to the following pull request regarding it[1].
In the end, the expectation is to have logs printed similar to the org.apache.synapse.transport.http.wire logs.
Expect to have the following printed.

1. Incoming and outgoing headers.
2. The payload/Body

[1]https://github.com/wso2-support/carbon-mediation/pull/408

Regards,
Deelaka
