### ISSUE TITLE
Wrong import syntax increases bundle size in devportal

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#9365]
### Describe your problem(s)
An improper import of an Mui Icon is unnecessarily increasing the size of the vendors~Apis~Landing bundle (17 MiB vs 97KiB)

ource/src/app/components/Apis/Listing/StarRatingBar.jsx

source/src/app/components/Apis/Details/StarRatingSummary.jsx

import is:
```
import { StarRating } from '@material-ui/icons';
```
instead of using:

```
import StarRating from '@material-ui/icons/StarRating';
```

**Comment by tmkasun** [comment]
This issue is only occurring in Webpack development build and this has stated in the [material-ui documentation](https://material-ui.com/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking) as well.

In the production build, the unused modules are removed with the tree-shaking techniques used in webpack and this has no effect on production build artifacts, Yet it's good if we can use avoid this entier icon set get bundled in the development build as well.

![image](https://user-images.githubusercontent.com/3313885/96085116-f2437300-0edd-11eb-9693-f91aa75f001d.png)

Closing the issue, As this is fixed in https://github.com/wso2/carbon-apimgt/pull/9310
