### ISSUE TITLE
Registry implementation of interface method org.wso2.carbon.apimgt.api.APIPersistence#getDocumentation(String apiId, String docId, Organization requestedOrg) doesn't need apiId to be passed

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#9388]
Registry implementation of interface method org.wso2.carbon.apimgt.api.APIPersistence#getDocumentation(String apiId, String docId, Organization requestedOrg) doesn't need apiId to be passed. But mongoDb impl will require it.

**Comment by malinthaprasan** [comment]
That is ok.
This is because the way we implemented this in registry based persistence doesn't required the apiID to locate documents. Documents can be located only using the docId. For mongoDB it is not. It is stored based on the apiId and also docId. As this is depending on the implementation, the Interface doesn't need to restrict to a single way hence it can include the both parameters. If any implementation doesn't need a certain parameter it can just ignore it.
