### ISSUE TITLE
Support selective API Gateway publishing for API Products

### ISSUE THREAD

**Issue by Arshardh** [wso2/product-apim#9445]
API products currently does not allow to be published to specific gateways selectively.

**Comment by dushaniw** [comment]
The fix will be as follows.

**Create API Product Wizard**
In this case publisher can select either of the following
1. Create -> Create an API Product in CREATED state with given all environments attached to the artifact
2. Create & Publish -> Create an API Product with the given environments and publish it to all the environments

![image](https://user-images.githubusercontent.com/12208083/127336951-778aae69-4c5a-4914-bfe3-0a47ea65b2fd.png)

**Environments for an API Product in CREATED state**
![image](https://user-images.githubusercontent.com/12208083/127337904-1d05ba92-ba8c-48b0-a860-fd1d10a009a2.png)


Added tooltip for Publish button since its not intuitive.
![Screenshot from 2021-07-28 20-02-22](https://user-images.githubusercontent.com/12208083/127341114-20bfabc2-8457-4cd4-90a8-4757a17b8333.png)


In this case, publisher can tick environments and perform either of the following options
1. Click Save -> Update the environments in API Product artifact. Do not publish to Gateway or Developer portal
2. Click Publish -> Update the environments in API Product artifact and publish to Gateway or Developer portal

**Environments for an API Product already in Published state**
![image](https://user-images.githubusercontent.com/12208083/127337867-05fec5b7-9be8-4df2-a000-9e8449c4da62.png)

In this case, publisher can tick environments and perform only the following.
1. Click Save -> Update the environments in API Product artifact and republish to Gateway and Developer portal

**Comment by dushaniw** [comment]
Already fixed in 4.0 and master
