### ISSUE TITLE
Creating roles for API subscriber

### ISSUE THREAD

**Issue by stefanonegri** [wso2/product-apim#9538]
### Description:
hello folks,
I was following the documentation here reported to create a new role (https://apim.docs.wso2.com/en/latest/administer/managing-users-and-roles/managing-user-roles/)
but once created the subscriber role, and added a user to it, I still can't log in the Developer Portal.
### Steps to reproduce:
Create a new role 'creator', assign Login and APIManage-API-Subscription permission. Create a new user and add the role creator. Log in the Dev Portal with the user just created: it fails with for insufficient privileges
### Affected Product Version:
WSO2 APIM 3.2.x

### Environment details (with versions):

---

**Comment by tmkasun** [comment]
Hi @stefanonegri 

After creating a new role, You have to assign necessary permissions to the new role from the admin portal. Otherwise, you will get an error saying `You don't have enough permissions to access the portal . . .`

As in the below image  goto admin portal -> click role permissions -> click on permissions button -> choose all permissions under `store`
and save

![image](https://user-images.githubusercontent.com/3313885/100041675-cfd33c80-2e2f-11eb-808e-07aa3a659aa0.png)

**Comment by stefanonegri** [comment]
will do. Thank you
*Stefano Negri*
Director - Solutions Architecture
Mob.: +491729035969

*WSO2 Germany GmbH*
c/o Bird & Bird LLP, Maximiliansplatz 22, 80333, Munich, Germany
Sitz in München / Registered in Munich, Germany
Amtsgericht Registergericht München/ Commercial Register, Munich Local
Court, HRB 244666
Geschäftsführer / Managing Directors: Charndika Arthanayake, Gamini. S.M.
Goonetilleke
