### ISSUE TITLE
Add document button is not getting disabled

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-apim#9544]
### Description:
1) Select the inline radio button first
2) then select the Support Forum radio button
3) Add document button is not disabled.
3) And also, the Add Document button is getting disabled once you click the URL radio button

**Comment by Sarangan0219** [comment]
This issue is not reproducible in the latest APIM pack.

![Screenshot from 2020-11-23 11-20-21](https://user-images.githubusercontent.com/60866295/99932410-eb7e0a80-2d7d-11eb-9ac8-b50d775d035a.png)

**Steps Followed:**

1. Select the inline radio button first
2. then select the Support Forum radio button
`
Add document` button is in a disabled state for all these steps.

**Comment by tmkasun** [comment]
@dileepagayan What is the API manager version you experienced this issue?

**Comment by Krishanx92** [comment]
Stale issue hence closing
