### ISSUE TITLE
Tenant Theme doc url not working in admin portal

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#9966]
### Description:
Tenant Theme doc url not working in admin portal

### Steps to reproduce:
1. Log in to admin portal using a tenant user
2. Select **Tenant Theme**
3. Select the **API Manager theme format** URL in the page. It redirects to homepage of apim 3.2

<img width="1219" alt="theme" src="https://user-images.githubusercontent.com/4861150/108191278-f48e3600-7138-11eb-8d31-ba96b3250ea5.png">

### Affected Product Version:
APIM 4.0.0 M7

**Comment by malinthaprasan** [comment]
Current link is : https://apim.docs.wso2.com/en/next/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme/#tenant-theming

Needs to point to: https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme/#tenant-theming

**Comment by tmkasun** [comment]
@malinthaprasan  I think we need to set the versioned URL in the master for the next release version, 

For example:

https://apim.docs.wso2.com/en/4.0.0/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme/#tenant-theming

otherwise latest will pointing whatever the latest doc at the time user visits the portal

We can merge https://github.com/wso2/carbon-apimgt/pull/10050 PR once the APIM 4.0.0 doc is public
