### ISSUE TITLE
Event publisher option is not available in the gateway profile mode

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/product-apim#9975]
### Description:
When APIM is started in the gateway-worker profile mode, event publisher option is not available in the management console. Adding event publisher is essential to enable message tracing. Due to the above limitation, users cannot enable message tracing in gw profile mode.

### Steps to reproduce:

1. Start the APIM in the gateway-worker profile.
2. Log in to the carbon management console and navigate to the Main -> Manage section.  
3. **Event** menu item is missing under the Manage section. Hence it is not possible to add event publishers.

### Affected Product Version:
APIM-2.1.0
APIM-2.6.0

**Comment by dushansilva** [comment]
The following jars are needed to be added to bundles.info file at minimum to fix this issue,
org.wso2.carbon.event.publisher.admin,5.1.42,../plugins/org.wso2.carbon.event.publisher.admin_5.1.42.jar,4,true
org.wso2.carbon.event.publisher.core,5.1.42,../plugins/org.wso2.carbon.event.publisher.core_5.1.42.jar,4,true
org.wso2.carbon.event.publisher.stub,5.1.42,../plugins/org.wso2.carbon.event.publisher.stub_5.1.42.jar,4,true
org.wso2.carbon.event.publisher.ui,5.1.42,../plugins/org.wso2.carbon.event.publisher.ui_5.1.42.jar,4,true
org.wso2.carbon.event.stream.admin,5.1.42,../plugins/org.wso2.carbon.event.stream.admin_5.1.42.jar,4,true
org.wso2.carbon.event.stream.persistence.stub,5.1.42,../plugins/org.wso2.carbon.event.stream.persistence.stub_5.1.42.jar,4,true
org.wso2.carbon.event.stream.stub,5.1.42,../plugins/org.wso2.carbon.event.stream.stub_5.1.42.jar,4,true
org.wso2.carbon.event.processor.manager.core,5.1.42,../plugins/org.wso2.carbon.event.processor.manager.core_5.1.42.jar,4,true
org.wso2.carbon.event.processor.common,2.1.23,../plugins/org.wso2.carbon.event.processor.common_2.1.23.jar,4,true
org.wso2.carbon.event.processor.manager.commons,5.1.42,../plugins/org.wso2.carbon.event.processor.manager.commons_5.1.42.jar,4,true
org.wso2.carbon.event.processor.stub,2.1.23,../plugins/org.wso2.carbon.event.processor.stub_2.1.23.jar,4,true
storm-core,0.10.1.wso2v1,../plugins/storm-core_0.10.1.wso2v1.jar,4,true
siddhi-core,3.2.3,../plugins/siddhi-core_3.2.3.jar,4,true
siddhi-query-api,3.2.3,../plugins/siddhi-query-api_3.2.3.jar,4,true
siddhi-query-compiler,3.2.3,../plugins/siddhi-query-compiler_3.2.3.jar,4,true

additionally we can add different adapter jars such as logger, this might be needed since only event adapter that is available is email
eg : org.wso2.carbon.event.output.adapter.logger,5.1.42,../plugins/org.wso2.carbon.event.output.adapter.logger_5.1.42.jar,4,true

After an internal discussion it was decided not to fix this issue since there are 15 new jars being added to the gateway and its best if we can avoid doing such changes to the gateway 

as a workaround if they need this feature they can use the default profile, or as an alternative feature observability feature should be looked at.
